### PR TITLE
fix: revise `encoding.color = {signal:...}` to be `{value: {signal:...}}`

### LINKED ISSUE #6433: Revise syntax for using signal in an encoding constant `value`.
Seeing  datum signal in https://github.com/vega/vega-lite/pull/6432 as   `encoding.color = {datum: {signal: ...}`

I think we should revise `encoding.color = {signal:...}` to be `encoding.color = {value: {signal:...}}` so it's consistent and easier to teach, though a bit more verbose.   

Basically, once we have signal as an official feature, we can just say `value` is a constant value in visual domain and `datum` is constant value in data domain, both of which support signals as their values.  (Instead of saying value signal use `{signal:...}` but datum signal needs nesting.)

### PR DESCRIPTION
**Pull request by kanitw**
fix #6433

Note that we'll still support conditional axis signal like this:

```
gridColor: {
  condition: {
    test: '<is major grid>',
    signal: 'majorGridColor' // this can also be `value: "#ddd"`
  },
  signal: 'gridColor'  // this can also be `value: "#eee"`
}
```

### CODE REVIEW

File: src/encoding.ts [hunk 1]
```diff
@@ -188,7 +188,7 @@ export interface Encoding<F extends Field> {
   color?:
     | ColorGradientFieldDefWithCondition<F>
     | ColorGradientDatumDefWithCondition<F>
-    | ColorGradientValueOrSignalDefWithCondition<F>;
```
Comment (kanitw) [inline src/encoding.ts:191]: I didn't like the fact that we have to do `ColorGradientValueOrSignalDefWithCondition` because once we expose signal as an official feature, value and signal will show up together in the docs.  

If want to keep signal def but separate value and signal in the property table, then we have to declare so many repetitive types.
For every variant of value or signal def (e.g., `ColorGradient`), we have to do:

```
XXXValueDefWithCondition
XXXSignalDefWithCondition
```

**Comment by domoritz** [comment]
Nice. I like that you delete more code than add.
