### PR TITLE
Do not group pathgroup by tooltip fields.

### LINKED ISSUE #4122: Line chart with tooltips is broken
```json
{
  "$schema": "https://vega.github.io/schema/vega-lite/v3.json",
  "description": "Stock prices of 5 Tech Companies Over Time.",
  "data": {"url": "data/stocks.csv", "format": {"type": "csv"}},
  "mark": "line",
  "encoding": {
    "x": {"field": "date", "type": "temporal", "axis": {"format": "%Y"}},
    "y": {"field": "price", "type": "quantitative"},
    "color": {"field": "symbol", "type": "nominal"},
    "tooltip": [
      {"field": "date", "type": "temporal"},
      {"field": "symbol", "type": "nominal"},
      {"field": "price", "type": "quantitative"}
    ]
  }
}
```

Somehow it has too many fields in the facet groupby (and also redundant fields).

### PR DESCRIPTION
**Pull request by domoritz**
Fixes #4122

### CODE REVIEW

File: src/compile/mark/mark.ts [hunk 1]
```diff
@@ -182,8 +182,9 @@ export function pathGroupingFields(mark: Mark, encoding: Encoding<string>): stri
       case 'text':
       case 'shape':
         return details;
-
       case 'tooltip':
+        // tooltip fields should not be added to group by
+        return details;
```
Comment (arvind) [inline src/compile/mark/mark.ts]: Do we need a separate `case`/`return` here, or could `tooltip` be moved to the previous block?
