### PR TITLE
fix: rule orientation for binned data (e.g., error bar for binned data)

### LINKED ISSUE #5489: Slanted error bars when data is binned
When plotting error bars on quantitative data that is binned, the error bars show up slanted.
Here's a minimalist reproduction that I've tested in the Vega online editor (this is the barley yield error bar example, just that the y-axis shows binned years rather than variety):
```json
{
  "$schema": "https://vega.github.io/schema/vega-lite/v4.json",
  "data": {"url": "data/barley.json"},
  "encoding": {"y": {"field": "variety", "type": "ordinal"}},
  "layer": [
    {
      "mark": {"type": "errorbar", "extent": "ci"},
      "encoding": {
        "x": {
          "type": "quantitative",
          "field": "yield",
          "scale": {"zero": false}
        },
        "y": {"type": "quantitative", "bin": true, "field": "year"}
      }
    },
    {
      "mark": {"type": "point", "color": "black", "filled": true},
      "encoding": {
        "x": {"type": "quantitative", "aggregate": "mean", "field": "yield"},
        "y": {"type": "quantitative", "bin": true, "field": "year"}
      }
    }
  ]
}
```
In this example I'd like to plot the barley yield for binned years. (It's binning only over single years, which doesn't really make sense, but illustrates the problem).
Here's the chart this specification produces for me:
image

Is there a way to work around this issue?

### PR DESCRIPTION
**Pull request by kanitw**
fix #5489

image

### CODE REVIEW

File: src/compile/mark/init.ts [hunk 1]
```diff
@@ -149,7 +149,8 @@ function orient(mark: Mark, encoding: Encoding<string>, specifiedOrient: Orienta
     // falls through
     case RULE:
       // return undefined for line segment rule and bar with both axis ranged
-      if (x2 && y2) {
+      // we have to ignore that case that the data are already binned though
```
Comment (domoritz) [inline src/compile/mark/init.ts]:
```suggestion
      // we have to ignore the case that data is already binned
```
