### PR TITLE
fix: support signals in view properties

### LINKED ISSUE #5962: Signals should also work for view properties, not just config
https://github.com/vega/vega-lite/pull/5888 introduced experimental support for signals for configs. However, one may want to set signals on normal properties.

```json
{
  "$schema": "https://vega.github.io/schema/vega-lite/v4.json",
  "description": "A simple bar chart with embedded data.",
  "data": {
    "values": [
      {"a": "A", "b": 28}, {"a": "B", "b": 55}, {"a": "C", "b": 43},
      {"a": "D", "b": 91}, {"a": "E", "b": 81}, {"a": "F", "b": 53},
      {"a": "G", "b": 19}, {"a": "H", "b": 87}, {"a": "I", "b": 52}
    ]
  },
  "mark": "bar",
  "view": {
    "fill": {"signal": "'red'"}
  },
  "encoding": {
    "x": {"field": "a", "type": "ordinal"},
    "y": {"field": "b", "type": "quantitative"}
  }
}
```

But this leads to 

```
...
  "encode": {"update": {"fill": {"value": {"signal": "'red'"}}}},
```

### PR DESCRIPTION
**Pull request by domoritz**
Fixes #5962

### CODE REVIEW

File: src/compile/model.ts [hunk 1]
```diff
@@ -311,12 +310,10 @@ export abstract class Model {
...
-    for (const property in baseView) {
-      if (hasOwnProperty(baseView, property)) {
-        const value = baseView[property];
-        if (value !== undefined) {
-          e[property] = {value};
-        }
+    for (const property of keys(baseView)) {
+      const value = baseView[property];
+      if (value !== undefined) {
+        e[property] = isSignalRef(value) ? value : {value};
```
Comment (kanitw) [inline src/compile/model.ts]: there is a helper method that we use everywhere.  valueOrSignal or the other way round.

Comment (domoritz) [reply src/compile/model.ts]: `signalOrValueRef`, which seems like the wrong name. I'll send a pull request.

**Comment by domoritz** [comment]
Done
