### PR TITLE
fix: use child signal for radius if faceted

### LINKED ISSUE #8754: facet fails on arc
Given the following vega-lite spec:
```json
{
  "$schema": "https://vega.github.io/schema/vega-lite/v5.6.1.json",
  "data": {
    "values": [
      {"t": 0, "v": 2, "c": "foo"},
      {"t": 1, "v": 2.5, "c": "foo"},
      {"t": 2, "v": 3, "c": "foo"},
      {"t": 3, "v": 4, "c": "foo"},
      {"t": 4, "v": 5, "c": "foo"},
      {"t": 5, "v": 5.5, "c": "foo"},
      {"t": 6, "v": 4, "c": "foo"},
      {"t": 7, "v": 3, "c": "foo"},
      {"t": 0, "v": 2, "c": "bah"},
      {"t": 1, "v": 2.5, "c": "bah"},
      {"t": 2, "v": 3, "c": "bah"},
      {"t": 3, "v": 4, "c": "bah"},
      {"t": 4, "v": 5, "c": "bah"},
      {"t": 5, "v": 5.5, "c": "bah"},
      {"t": 6, "v": 4, "c": "bah"},
      {"t": 7, "v": 3, "c": "bah"}
    ]
  },
  "mark": {"type": "arc"},
  "encoding": {
    "color": {"field": "v", "type": "quantitative"},
    "column": {"field": "c", "type": "nominal"},
    "radius": {"field": "v", "type": "quantitative"},
    "theta": {"field": "t", "type": "nominal"}
  },

}
```
I see:
image

[Open the Chart in the Vega Editor](https://vega.github.io/editor/#/url/vega-lite/N4IgJAzgxgFgpgWwIYgFwhgF0wBwqgegIDc4BzJAOjIEtMYBXAI0poHsDp5kTykBaADZ04JAKyUAbJQCMlAFYQ2AOxAAaEABMkmFKlDEkghnAhoA2qExoADBuJoATBqhoQAMzZsQAXzVW0GXsnSjEXN09vPwDUZxAHVABmcPRI338QayTg1AAWFI8vdJj8+LQwkFdUoujM8pyJCqrCqIysyRzS5rTarIB2HOTKiJq22xy45qYkGGK61CCy2NCC6dnep0HVmbmsoYSutzXdtFKEpqOdjdQK85Xh9GPrjqXDx6ux1AGloamrgF0-CBkAAnADWaCsAE8cHA3EgQa4gXBlFA2JoaMoyJDKmxBGwQTj3DQ4IJNG4HBpMDC4egAI4MJDKTB0HQ0UjpXHGBCqfQeElktyuKk0tzKNgITFGTkgpAYhhmPnE0nk9CUzKi+mM5mslkcoH0OC6IkC1V1EWwsUSqWCXw+HxAA)

It seems it is not possible to facet an arc-mark. 

Removing the `"column": {"field": "c", "type": "nominal"}` gives a single chart:
image

Altair python code:
```python
import altair as alt
import pandas as pd

base = pd.DataFrame(
    {"t": range(8),
     "v": [2, 2.5, 3, 4, 5, 5.5, 4, 3]}
)
cA = base.copy()
cA.loc[:, 'c'] = 'foo'
cB = base.copy()
cB.loc[:, 'c'] = 'bah'

source = pd.concat((cA, cB))
source.head()

arcs = alt.Chart(source).mark_arc().encode(theta="t:N", radius="v:Q", color="v:Q", column="c:N")
arcs
```

Related: https://github.com/vega/vega-lite/issues/3729

### PR DESCRIPTION
**Pull request by ChiaLingWeng**
close #8754 
I found that the range for radius using width and height without checking if the model  is faceted
https://github.com/vega/vega-lite/blob/c33f46bad7f80f779e463a8a36481f888f18e222/src/compile/scale/range.ts#L311-L314

### CODE REVIEW

File: src/compile/scale/range.ts [hunk 1]
```diff
@@ -306,11 +307,12 @@ function defaultRange(channel: ScaleChannel, model: UnitModel): VgRange {
...
     case RADIUS: {
       // max radius = half od min(width,height)
+
       return [
         0,
         new SignalRefWrapper(() => {
-          const w = model.getSignalName('width');
-          const h = model.getSignalName('height');
+          const w = isFacetModel(model.parent) ? model.getSignalName('child_width') : model.getSignalName('width');
+          const h = isFacetModel(model.parent) ? model.getSignalName('child_height') : model.getSignalName('height');
```
Comment (domoritz) [inline src/compile/scale/range.ts:315]:
```suggestion
          const w = model.getSignalName(isFacetModel(model.parent) ? 'child_width' : 'width');
          const h = model.getSignalName(isFacetModel(model.parent) ?'child_height' : 'height');
```

**Review by domoritz — APPROVED** [review]
