### PR TITLE
fix: respect offset for mark.x/y

### LINKED ISSUE #5331: xOffset/yOffset cannot be applied to static x/y markdef properties
If I want to place a circle mark just below the bottom of the view, I can do:

```json
{
    "data": {
        "values": [0]
    },
    "mark": {
        "type": "circle",
        "size": 250,
        "yOffset": 25
    },
    "encoding": {
        "y": { "value": "height" }
    }
}
```

which will yield the following correct result:

visualization

However, if want to express the same thing statically in the markdef (without any encodings), I should be able to do:

```json
{
    "data": {
        "values": [0]
    },
    "mark": {
        "type": "circle",
        "size": 250,
        "y": "height",
        "yOffset": 25
    }
}
```

However, the offset is not applied in this case:

visualization-2

It seems that `yOffset` is only applied to a `y` encoding value, but it should also apply to a static `y` markdef property, because otherwise there is no way to position a static annotation against the height of a container.

The same goes for `x` & `xOffset`.

### PR DESCRIPTION
**Pull request by kanitw**
fix #5331

### CODE REVIEW

File: src/compile/mark/valueref.ts [hunk 1]
```diff
@@ -373,7 +372,16 @@ export function midPoint({
...
   }
 
-  return isFunction(defaultRef) ? defaultRef() : defaultRef;
+  const ref = isFunction(defaultRef) ? {...defaultRef(), ...(offset ? {offset} : {})} : defaultRef;
+
+  if (ref) {
+    // for non-position, ref could be undefined.
+    return {
+      ...ref,
+      ...(offset ? {offset} : {})
```
Comment (domoritz) [inline src/compile/mark/valueref.ts]: What if the offset is 0? 

Should this be:

```suggestion
      ...(offset != null ? {offset} : {})
```

Comment (kanitw) [reply src/compile/mark/valueref.ts]: If offset is 0, you can safely omit the offset.

Comment (domoritz) [reply src/compile/mark/valueref.ts]: Good. Just wanted to make sure. Maybe it's worth a comment here since `x ? .. : ...` always makes my alarm bells go off.
