### PR TITLE
fix: apply background only once

### LINKED ISSUE #5466: The background color should only be set in the config or at the top level
We are currently setting it both at the top-level and in the config that is part of the compiled spec.

### PR DESCRIPTION
**Pull request by domoritz**
fixes #5466

### CODE REVIEW

File: src/config.ts [hunk 1]
```diff
@@ -373,6 +374,8 @@ export function stripAndRedirectConfig(config: Config) {
   // affect header labels, which also uses `title` directive to implement.
   redirectConfig(config, 'title', 'group-title');
 
+  // Remove background config since we apply it to the spec.
```
Comment (kanitw) [inline src/config.ts]: Why is this comment here, not above in `VL_ONLY_CONFIG_PROPERTIES`?

Comment (domoritz) [reply src/config.ts]: Good catch. Fixed.
