### PR TITLE
Better error bar and error band tooltip

### LINKED ISSUE #4261: Tooltip for box plots is weird
It currently only shows only a few variables.

image

1) the "population" title is a bit wrong
2) only two fields are shown on hover although box plots are basically visual version of a 5-number summary.  

Ideally, it should explicitly says median_people, q3_people, etc.  (or even better, show "Q3 of people", "Median of people".)

### PR DESCRIPTION
**Pull request by chanwutk**
fix #4261

### CODE REVIEW

File: src/compositemark/common.ts [hunk 1]
```diff
@@ -23,6 +31,31 @@ export type GenericCompositeMarkDef<T> = GenericMarkDef<T> &
     clip?: boolean;
   };
 
+export interface CompositeMarkTooltipSummary {
+  fieldPrefix: string;
+  titlePrefix: string;
+}
+
+export function getCompositeMarkTooltip(
```
Comment (kanitw) [inline src/compositemark/common.ts]: What is `tooltipSummaryMap` btw?  Why `-Map` suffix?   Why not `tooltipSummaries`?

File: src/compositemark/errorbar.ts [hunk 2]
```diff
@@ -107,9 +110,9 @@ export function normalizeErrorBar(
     ...outerSpec,
     transform,
     layer: [
-      ...makeErrorBarPart('ticks', tick, 'lower'),
-      ...makeErrorBarPart('ticks', tick, 'upper'),
-      ...makeErrorBarPart('rule', 'rule', 'lower', 'upper')
+      ...makeErrorBarPart('ticks', tick, 'lower', null, tooltipEncoding),
```
Comment (kanitw) [inline src/compositemark/errorbar.ts]: I think it's worth making `makeErrorBarPart` take parameters as an object since this object this method is getting a bit hard at this point. 

(I have wanted to change this earlier, but haven't got the chance yet.)

File: src/compositemark/errorbar.ts [hunk 3]
```diff
@@ -340,10 +349,29 @@ export function errorBarParams<
...
+export function errorBarTooltipEncoding(
+  continuousAxisChannelDef: PositionFieldDef<string>,
+  encodingWithoutContinuousAxis: Encoding<string>
+): Encoding<string> {
+  const tooltopSummaryMap: CompositeMarkTooltipSummary[] = [
+    {fieldPrefix: 'upper', titlePrefix: 'Upper error'},
+    {fieldPrefix: 'lower', titlePrefix: 'Lower error'}
+  ];
+
+  const tooltip: TextFieldDef<string>[] = getCompositeMarkTooltip(
```
Comment (kanitw) [inline src/compositemark/errorbar.ts]: Why shouldn't `getCompositeMarkTooltip` return the output wrapped with `{tooltip: ...}` already? 

Also, I wonder if `errorBarTooltipEncoding` needs to be a separate method at all?   (Same for box)

It seems like you only need to define `errorBarTooltipSummaries()` (I think the name `-Map` is confusing) and just call `getCompositeMarkTooltip` directly.

File: src/compositemark/errorbar.ts [hunk 4]
```diff
@@ -340,10 +349,29 @@ export function errorBarParams<
...
+    tooltipEncoding
   };
 }
 
+export function errorBarTooltipEncoding(
+  continuousAxisChannelDef: PositionFieldDef<string>,
+  encodingWithoutContinuousAxis: Encoding<string>
+): Encoding<string> {
+  const tooltopSummaryMap: CompositeMarkTooltipSummary[] = [
+    {fieldPrefix: 'upper', titlePrefix: 'Upper error'},
```
Comment (kanitw) [inline src/compositemark/errorbar.ts]: Title "Upper/lower error" is confusing -readers won't get whether the error bar encodes Stdev, Stderr, CI. (It's basically confusing.) 

For pre-aggregated case, better not provide special title and use original field name. 

For aggregating case, we should provide information about what error bar presents.  For example, we could  say `mean(x)+stdev(x) = ...`, `mean(x) - stdev(x)` = ...Alternatively, we could just directly set `titlePrefix: titlecase(aggregate)` in the tooltip and show the error instead of upper/lower (so we get `Stdev of X`) and reduce the complex +/- thing. 

cc: @domoritz  Any thoughts

Comment (kanitw) [reply src/compositemark/errorbar.ts]: It might be worth looking at how other systems display tooltips for error bars too.  

I suspect that some might even says  "10 ± 5".  So another alternative is 
`Mean of x ± Stdev of X:   10 ± 5`.   

Right now I think this might be the best, but would require some custom signal that we couldn't do without a signal / expression support yet.

File: test/compositemark/errorbar.test.ts [hunk 5]
```diff
@@ -62,8 +62,8 @@ describe('normalizeErrorBar with raw data input', () => {
             y2: {field: 'upper_people', type: 'quantitative'},
             x: {field: 'age', type: 'ordinal'},
             tooltip: [
-              {field: 'upper_people', title: 'Upper error of people', type: 'quantitative'},
-              {field: 'lower_people', title: 'Lower error of people', type: 'quantitative'},
+              {field: 'upper_people', title: 'mean + stderr of people', type: 'quantitative'},
```
Comment (kanitw) [inline test/compositemark/errorbar.test.ts]: We use Titlecase for standard title names.  (e.g., `"Mean of x"`)

File: test/compositemark/errorbar.test.ts [hunk 6]
```diff
@@ -668,8 +668,8 @@ describe('normalizeErrorBar with aggregated upper and lower bound input', () =>
             y2: {field: 'upper_people', type: 'quantitative'},
             x: {field: 'age', type: 'ordinal'},
             tooltip: [
-              {field: 'upper_people', title: 'Upper error of people', type: 'quantitative'},
-              {field: 'lower_people', title: 'Lower error of people', type: 'quantitative'},
+              {field: 'lower_people', title: 'people', type: 'quantitative'},
```
Comment (kanitw) [inline test/compositemark/errorbar.test.ts]: People and people2 is worse than upper/lower error

File: examples/specs/normalized/layer_point_errorbar_ci_normalized.vl.json [hunk 7]
```diff
@@ -41,12 +41,12 @@
               {
                 "field": "upper_yield",
                 "type": "quantitative",
-                "title": "Upper error of yield"
+                "title": "ci1 of yield"
```
Comment (kanitw) [inline examples/specs/normalized/layer_point_errorbar_ci_normalized.vl.json]: ci0 / ci1 are not naturally understood operations (very specific to Vega [for "The lower boundary of the bootstrapped 95% confidence interval of the mean field value."](https://vega.github.io/vega/docs/transforms/aggregate/#ops))

Perhaps, "Mean of <fieldname> (Upper/Lower bound of 95% CI)". 
(Though I think it's still a bit too long.)  

@domoritz  Any suggestion?

Comment (kanitw) [reply examples/specs/normalized/layer_point_errorbar_ci_normalized.vl.json]: Actually, if users directly uses ci, they gets this title as well. So perhaps, we can keep it like this in this PR.  

(But make sure that this title thing is generated from a common code (by calling [`title()` in `fielddef.ts`](https://github.com/vega/vega-lite/blob/master/src/fielddef.ts#L524)).  

We can then consider if we should revise default title for `ci0`/`ci1`.

File: test/compositemark/errorbar.test.ts (hunk 6 above)
Comment (chanwutk) [reply test/compositemark/errorbar.test.ts]: This is ranged error bar case, should we use the original field name?

Comment (kanitw) [reply test/compositemark/errorbar.test.ts]: The axis title should just be the field name (e.g., `people`). 

However, the title in the tooltip should be quite descriptive. 
(What does the error exactly represent? -- ci0/ci1, mean+stdev/err?)

File: test/compositemark/errorbar.test.ts (hunk 5 above)
Comment (chanwutk) [reply test/compositemark/errorbar.test.ts]: Would you prefer `Mean(people) + Stderr(people)` or `Mean + Stderr of people`?

**Comment by kanitw** [comment]
Mean + stderr of people, with small s — consistent with other titles

**Comment by kanitw** [comment]
Use original field names then.

File: src/compositemark/errorbar.ts (hunk 2 above)
Comment (chanwutk) [reply src/compositemark/errorbar.ts]: Can you clarify this a bit more?

Comment (kanitw) [reply src/compositemark/errorbar.ts]: See 86eae67bb905be5b6582bf27d2e60f6635918862 for example.  I did the same thing to `tickCount()` there so it will enforce us to include parameter names.

Right now this method is extremely hard to read.  It's hard to remember what the first 'rule' and the second 'rule' are for. By forcing them to be an object, we can understand the parameter name right away.

Just like in Python `f(x=3,y=4,z=5,opt={})` is clearer than `f(3,4,5,{})` as we know that the first parameter is `x`, second is `y` and so on.  For method with 1-2 parameters, this isn't so important. But once we have several, it's becoming quite hard to read.

Comment (kanitw) [reply src/compositemark/errorbar.ts]: https://basarat.gitbooks.io/typescript/content/docs/tips/functionParameters.html

**Comment by kanitw** [comment]
Rebase?

**Comment by domoritz** [comment]
This seems unintended, no? 

screen shot 2018-12-26 at 13 33 02

**Comment by chanwutk** [comment]
I will fix it.

File: examples/compiled/errorband_2d_horizontal_color_encoding.vg.json [hunk 8]
```diff
@@ -39,7 +39,7 @@
           "orient": {"value": "vertical"},
           "fill": {"value": "black"},
           "tooltip": {
-            "signal": "{\"Miles per Gallon (95% CIs)\": format(datum[\"lower_Miles_per_Gallon\"], \"\"), \"upper_Miles_per_Gallon\": format(datum[\"upper_Miles_per_Gallon\"], \"\"), \"Year (year)\": timeFormat(datum[\"year_Year\"], '%Y')}"
+            "signal": "{\"Ci1 of Miles_per_Gallon\": format(datum[\"upper_Miles_per_Gallon\"], \"\"), \"Ci0 of Miles_per_Gallon\": format(datum[\"lower_Miles_per_Gallon\"], \"\"), \"Year (year)\": timeFormat(datum[\"year_Year\"], '%Y')}"
```
Comment (domoritz) [inline examples/compiled/errorband_2d_horizontal_color_encoding.vg.json]: Why "Ci" instead of "CI"? It stands for Confidence Interval.

Comment (kanitw) [reply examples/compiled/errorband_2d_horizontal_color_encoding.vg.json]: As commented above, we should systematically revise title of ci0/ci1 for both composite mark and general operation in a separate PR.

Comment (domoritz) [reply examples/compiled/errorband_2d_horizontal_color_encoding.vg.json]: Okay, I'll let you make the call on this or then.

File: test/compositemark/errorbar.test.ts [hunk 9]
```diff
@@ -1121,4 +1272,61 @@ describe('normalizeErrorBar with aggregated error input', () => {
...
+    );
+
+    const layer = isLayerSpec(outputSpec) && outputSpec.layer;
+    expect(layer).toBeTruthy();
+    for (const unitSpec of layer) {
+      const encoding = isUnitSpec(unitSpec) && unitSpec.encoding;
+      expect(encoding).toBeTruthy();
+      const tooltip = encoding.tooltip;
+      expect(tooltip).toEqual([
+        {field: 'upper_people', title: 'people + people_error1', type: 'quantitative'},
```
Comment (kanitw) [inline test/compositemark/errorbar.test.ts]: Why is there no tooltip for `y` if `y`, `yError`, and `yError2` are all provided?

Also, why is extent specified when users directly specify yError/yError2?

**Comment by kanitw** [comment]
When we know the center, I think the tooltip should show the center as well. 

image

(Otherwise, the audience has to manually calculate the center in their head.)

**Comment by chanwutk** [comment]
Since we have to aggregate the center value for error bar with `stdev` and `stderr`, would it be useful to show the center value of the bar in tooltip as well.
And for the errorbar with `ci` and `iqr`, should we also aggregate for mean and median and include them in tooltip?
