### PR TITLE
Make stacked area chart with imputation render correctly.

### LINKED ISSUE #1805: Broken Stacked Bar Chart
```
{
  "data": {"url": "data/movies.json"},
  "mark": "area",
  "encoding": {
    "x": {
      "bin": {"maxbins": 10},
      "field": "IMDB_Rating",
      "type": "quantitative"
    },
    "color": {
      "field": "Source",
      "type": "nominal"
    },
    "y": {
      "aggregate": "count",
      "field": "*",
      "type": "quantitative"
    }
  }
}
```
vega_editor

### PR DESCRIPTION
**Pull request by kanitw**
1. Make pathOrder's collect transform always included in the last data source (can be raw/summary/stacked)
2. Make stack's `impute` and `stack` transforms always include both binned field's start and end

vega_editor

Fix #1805

### CODE REVIEW

File: src/compile/data/data.ts [hunk 1]
```diff
@@ -152,22 +152,13 @@ export function assembleData(model: Model, data: VgData[]) {
...
-    }
-
-    // Path Order
-    const pathOrderCollectTransform = pathOrder.assemble(component.pathOrder);
-    if (pathOrderCollectTransform) {
-      dataTable.transform = (dataTable.transform || []).concat([pathOrderCollectTransform]);
-    }
-  } else {
-    if (keys(component.nonPositiveFilter).length > 0) {
+    } else { /* istanbul ignore else: should never reach here */
```
Comment (domoritz) [inline src/compile/data/data.ts]: tricking cover, I see :-P

Comment (kanitw) [inline src/compile/data/data.ts]: lol you're welcome to add a test for this.  I'm not gonna do it.
