### PR TITLE
Legend type fix

### LINKED ISSUE #4380: We should not set the symbol encoding in the legend
See [this example](https://vega.github.io/editor/#/url/vega-lite/N4KABGBEDGD2B2AzAlgc0gLjMSA3ZApgO6baRHIAmALgBakDMADEwDRS0Fq3WkBMLAL6DW4KJQCG1CaRzwJAWwKlIk6QFoAHAwDsAIwKaAbE0Q6jDPmYCMEppU0BOc9E13rmj00gixkBRIATgDWKtDIgdAANsqiEJAE8HCUyPDoWKAQ8XBRsIGyYllQ1ACeAA7KWJAAjgCuEvDUyNJNuLGFWZAoBFGUKgDOyABe7UXxMaiJfRmQTdQxKpDskKiBEimJ1AAyiah0-EJxY5D90BILM6UVKrnogh2+RZAAHgVjxeWVUHUNc1LIbSWHXiEmeyH6slmzQuUAAokE6OoALKwNqBADk-TAABFwdIkrEoKsqKREOd+gRHsdur0VHpUpAHkd4iU3scrl8avVGs1-oDmZ1QeDIXMYZAAHK1BQGQJgWCIMAASXg-Xx0AIEOWxMoAHkyhJwqVSEwAHRGKlPGnTKBwWqNIHvE5nGE4Dk3WB3B5iKmQAAkp04ARUPGoZX6GAA9BG2qgJCbUM1aLU9CbkLAIwGCAFowRY+oos0CNGGCaAFb9BAO8RSCQU6gQjIdVQ1rS6AzGUzmSw2OwOZxGVzuTyabxYADawLIgxGjCYmgArEYjNYTdZHPOACw6bR8TTLW32rC6TQbthQenwY0mlhMPgb5fzi1ZHDTr58JcsRx8E0CJeOTQnou+6wHavBYNY1h8I4DDLBeV43sOj4ChAL7DG+94bruG4mhung6POUEeEYwGgaQ86OI4Z6QHBWCmiw1gMEYSGTqhM5YHwDDWDo76aCaujONo87mCRh5gKeS6wQytHXkwa7WMx7ysW+1hbkxjg4XwQnvipfB8CJYFgO+87WJJl7SSwd5MU+KEnGhpAeNYTD-kYOEEXeOhrnO+kHFupnwUwzBORRwUhcFOjWVOdngQBYUmtxS5cfOxkbt54GLiZ55SWAdEBUlCljEp9maHwOgMJuZoEY4G6WBY86pWAKmOX55lMBujn5UUhXgToG7zgwnjXtYRiUf+OheTaIGiRBTHNdlMn3klEVdQ1Ri9VV86ripDBVcVJ71QuGXUVlOUEUttlsStm7-thi4blVDAMNVKUTaRWBjcRmVmXNLBCb1Z2vvZm4CK1Zobluxkjc9MCTQZBFQzR31MEYUEdc+51fENYPFaa5jLnewUfdDr1iSws05UYgH-VFDXkfOc4uSpFM9SF9W7nun3+aVjhUxdmNMLj16rcYuFMXVL2ibpekcy1OjQXTN4Kze1g8xjxWWJxMmMSpvXCeLBlDYTCM5SeC4q-Z-5uSuQ1MJuTN3fVkHs0dX05ZRDBm+B-4QfJq6lXwOkLo4+3w8dMnrvhHsNSOQkAXF8lCboY1i0TonLmTg2yfjoXZ5Ha5dsw16y+YnnJweBmYenslI6jNkA+ByPDUjq5JY5AinlDZekPb0vfRBfC584skLia2gAWPAGlzD-A6JXEER8hkUXQII5ySadMeZhC49azh1G4NHEDxY61xcu2dB3r-DJ3vmemwvy3+61p7qX1FOYe1HdT57s+PZHD86D1LlqqVTah4B2M8e50QYuuXO25WpVQ0pPYmTUIGDT+nfdG5sHq3m-MwB6eCHqIKmlfUOsk6by0VorZW6C65RwIrtH8X4t46UJp3cCIcXaDUXAPPCNtrzGCXAI1aDtiEcNkg+X+d4vAlgXHlPKLDP5gHPs7eCQ1wrUOprpbQnEVzOHau+TiMEL5fxQbJbiNdF7KV6ouHGd1s6EP1rvEhXERwUIoe7dRS8nIeEwnxJyuhyFSxTvrQ2TjtC2LPsFTQv9ka4Xgc4f+CSEn1SUdfDw3MPEY1KipYeWlJaS2SbPdav9yJflKquQigjwFBPsoE1JESz5qJYhg9iXEHomEGoIwRBSTECEWhky+AV-YbVlmDUZYNunKPMg-cx99mZaL4vY+yVFr7+3NP0lpTgAI6DjpofCCtFlYCdisoZv9tzQQ8HFbieTdKGOqVgFJJDdLDXqZE3+ngVJOV9g0+qIj4IcU0sUzwzBvwEWYOYL8jEHa3JWf1aJWiwY-lcfzCZKygHRNPLs4Zml6rsL+XdX+X5MKOBcpYA5YAjmPM3DM5phlSpnOwsjMlITRHviRRQ-u6zDKJQEOpBi+C8EoseaLaJrSlwn0xftSuJUqFNJofJTiJ4qKsIao4ll5hqU0JKtxauJpHCHWVb8qZ2M2U3ncbKjRTgOI+0hUYsAhrvq7nnua3mG9GIlhtlo-l9VmV-OghIvxFhVxIyzhRKpyqKUsotm8kwpCR7Yttbi8yzANy-xvBYU01zrmCtEcwaBnL3xPTKmvTpS4w0KJ9UmlSGrqaMT6tVdSvVWaV0sLnVaslcJr35XgwJyroUkNJdWi6zAVL4Qbbcg1zbOImpvCmzlkFbb-kLmSxN302mDoxvOGK-s4pdoeh-Ymfac2YUjroI+24fwO2beDE9VyCJ0RLUufdolD3wTKmaxSNLLZNyUcq2p-bN3rsYCeTRK4XFuMvSYxis7nXoSnT4n9Ci-05uGoBjZUFfFsvHYh5tTqP1yvuuRbZWHiZIdfdHVtUFtn4SbSYjFkddn-xHi8p2yrVXwTBmsmDgMLAuTLUgyuvV5IwIASPCDkzvo62nT9Al5hVxievveKJc7OKLhkmyntCi2PmS3Okrj7EKYljJVpiT65UOKPkjgk1+rsMmLplZTldNjAXttcZuixk1wvIopxvD1MnBGD41NSuxlcMFRpRBJGK4jNBd3PRucDbyEUOsyRoLBDI7QSbqeNlSWJZBbBo+DoABdb0IBBBAA).

### PR DESCRIPTION
**Pull request by domoritz**
Compute legend type correctly. Fixes #4380.

### CODE REVIEW

**Comment by domoritz** [comment]
Contains #4381

File: src/compile/legend/parse.ts [hunk 1]
```diff
@@ -171,7 +168,7 @@ function getProperty<K extends keyof VgLegend>(
           legend,
           legendConfig,
           channel,
-          scaleType: model.getScaleComponent(channel).get('type')
+          scaleType: scaleType
```
Comment (kanitw) [inline src/compile/legend/parse.ts]: remove `: scaleType`

File: src/compile/legend/encode.ts [hunk 2]
```diff
@@ -18,7 +18,16 @@ import {getFirstDefined, keys} from '../../util';
 import {applyMarkConfig, timeFormatExpression} from '../common';
 import * as mixins from '../mark/mixins';
 import {UnitModel} from '../unit';
+import {ScaleChannel} from './../../channel';
 import {LegendComponent} from './component';
+import {defaultType} from './properties';
+
+function type(legendCmp: LegendComponent, model: UnitModel, channel: Channel) {
```
Comment (kanitw) [inline src/compile/legend/encode.ts]: channel here should be `ScaleChannel` otherwise it can't have a legend.

File: src/compile/legend/parse.ts (hunk 1 above)
Comment (domoritz) [reply src/compile/legend/parse.ts]: done already, I'll make this change in your PR

File: src/compile/legend/encode.ts (hunk 2 above)
Comment (domoritz) [reply src/compile/legend/encode.ts]: Done

**Comment by domoritz** [comment]
Rebased onto master after merging #4381

**Comment by kanitw** [comment]
Since you rename the files, it's hard to see the diffs. Can you separate the renaming to later?

**Comment by domoritz** [comment]
I manually deleted the files that should be gone. Now you see it was really just a rename.
