### PR TITLE
fix: correct references to flattened fields in selection signals.

### LINKED ISSUE #5334: Selections are not working with nested data
For example

```json
{
  "$schema": "https://vega.github.io/schema/vega-lite/v3.json",
  "selection": {
    "grid": {
      "type": "interval",
      "bind": "scales"
    }
  },
  "data": {
    "values": [
      {"nested":{ "a": "1", "b": 28}},
      {"nested":{ "a": "2", "b": 55}},
      {"nested":{ "a": "3", "b": 43}},
      {"nested":{ "a": "4", "b": 91}},
      {"nested":{ "a": "5", "b": 81}},
      {"nested":{ "a": "6", "b": 53}},
      {"nested":{ "a": "7", "b": 19}},
      {"nested":{ "a": "8", "b": 87}},     
      {"nested":{ "a": "8", "b": 52}}
    ]
  },
  "mark": "point",
  "encoding": {
    "y": {
      "field": "nested.a",
      "type": "quantitative"
    },
    "x": {
      "field": "nested.b",
      "type": "quantitative"
    }
  }
}
```

from https://github.com/vega/vega-lite/issues/4517#issuecomment-524568226

### PR DESCRIPTION
**Pull request by arvind**
Fields are only flattened if they participate in encoding rules. Thus, we continue to use bracket notation to access datum values in signal expressions as we cannot be guaranteed that the flattened field will be present. However, the field name stored as part of a SelectionProjection will *always* use dot notation as these names are either returned to us flattened by `model.vgField` or users explicitly specify them in the input spec (in which case, dot notation is their only recourse). Thus, when referencing the field via a selection's top-level signal, we just directly access the flattened field name, rather than unpacking it via bracket notation.

Fixes #5334.

### CODE REVIEW

**Comment by domoritz** [comment]
Looks good. Are you adding flattening for fields that are only referenced in selections as well?

**Comment by arvind** [comment]
I'm not planning to primarily due to time constraints (with my limited time, I'd rather push forward on code paths I'm already familiar and this felt like a principled fix rather than a hack/workaround).

**Comment by domoritz** [comment]
Okay. Can you explain what you meant by "this PR felt like a principled fix rather than a hack/workaround"?

**Comment by arvind** [comment]
Sure -- I mean that the description/reason I gave when opening this PR feels principled in the sense that selection signals do not need to make any assumptions about what is or isn't happening to the `datum`. Instead, selections can remain agnostic/independent about whether any flattening has occurred and react purely based on what the user specifies (which matches what is returned by `model.vgField`).

**Comment by domoritz** [comment]
Just to clarify, if the user starts with this spec.

```json
{
  "$schema": "https://vega.github.io/schema/vega-lite/v3.json",
  "selection": {
    "grid": {
      "type": "multi", "fields": ["nested.b"]
    }
  },
  "data": {
    "values": [
      {"nested":{ "a": "1", "b": 28}},
      {"nested":{ "a": "2", "b": 55}},
      {"nested":{ "a": "3", "b": 43}},
      {"nested":{ "a": "4", "b": 91}},
      {"nested":{ "a": "5", "b": 81}},
      {"nested":{ "a": "6", "b": 53}},
      {"nested":{ "a": "7", "b": 19}},
      {"nested":{ "a": "8", "b": 87}},     
      {"nested":{ "a": "8", "b": 52}}
    ]
  },
  "mark": "point",
  "encoding": {
    "y": {
      "field": "nested.a",
      "type": "quantitative"
    },
    "x": {
      "field": "nested.a",
      "type": "quantitative"
    }
  }
}
```

And now they add a calculate transform to derive fields `nested.aa` and `nested.bb`. 

In the spec below, the user has to know that they have to write `"fields": ["nested\\.bb"]` instead of `"fields": ["nested.bb"]` in the selection. They don't need to change anything in the encoding. 

```json
{
  "$schema": "https://vega.github.io/schema/vega-lite/v3.json",
  "selection": {
    "grid": {
      "type": "multi", "fields": ["nested.bb"]
    }
  },
  "data": {
    "values": [
      {"nested":{ "a": "1", "b": 28}},
      {"nested":{ "a": "2", "b": 55}},
      {"nested":{ "a": "3", "b": 43}},
      {"nested":{ "a": "4", "b": 91}},
      {"nested":{ "a": "5", "b": 81}},
      {"nested":{ "a": "6", "b": 53}},
      {"nested":{ "a": "7", "b": 19}},
      {"nested":{ "a": "8", "b": 87}},     
      {"nested":{ "a": "8", "b": 52}}
    ]
  },
  "transform": [{
    "calculate": "datum.nested.a", "as": "nested.aa"
  }, {
    "calculate": "datum.nested.b", "as": "nested.bb"
  }],
  "mark": "point",
  "encoding": {
    "y": {
      "field": "nested.aa",
      "type": "quantitative"
    },
    "x": {
      "field": "nested.aa",
      "type": "quantitative"
    },
    "color": {
      "condition": {"selection": "grid", "value": "red"}
    }
  }
}
```

**Comment by arvind** [comment]
Thanks for that example, @domoritz! That helped me understand the full scope of flattening. And it turns out updating `formatparse` wasn't as hard/as much work as I'd initially feared, yay! Updated this PR to more thoroughly address this issue, with corresponding test cases. So it should be ready for re-review.

**Comment by domoritz** [comment]
The second example in https://github.com/vega/vega-lite/pull/5351#issuecomment-525977832 still doesn't work for me. Clicking the circles doesn't make them red. 

If I replace

```json
{
      "name": "grid_tuple_fields",
      "value": [{"type": "E", "field": "nested.bb"}]
    },
```

with

```json
{
      "name": "grid_tuple_fields",
      "value": [{"type": "E", "field": "nested\\.bb"}]
    },
```

in the generated Vega, it works.

File: src/compile/data/parse.ts [hunk 1]
```diff
@@ -322,6 +322,7 @@ export function parseData(model: Model): DataComponent {
   }
 
   head = ParseNode.makeImplicitFromEncoding(head, model, ancestorParse) || head;
```
Comment (domoritz) [inline src/compile/data/parse.ts]: I believe that we may create unnecessarily flattening for fields that are already flattened in `makeImplicitFromEncoding`. I see three solutions. First, we could extract the code that computes `implicit` for encodings and selections and then call `makeWithAncestors` once for a single implicit dict. Second, makeImplicitFromEncoding could return its `implicit`, which we pass to `makeImplicitFromSelection`, and there we ignore fields that are already flattened otherwise. Second, you could merge `makeImplicitFromEncoding` and `makeImplicitFromSelection` so that they share the same `implicit` dict. I guess this is like the first approach but encapsulates the logic. I'd prefer the first as it's most explicit.

Comment (arvind) [reply src/compile/data/parse.ts]: Thanks for the comment. Yes, I'd thought about this and tested it informally (e.g., using the spec below in which both `makeImplicitFromEncoding` and `makeImplicitFromSelection` are called). As far as I could tell, duplicate flattening does _not_ occur. But, I wasn't sure how to formally test this as a unit test (i.e., focused on just parsing/assembling the `ParseNode`). I'm happy to add a test case that parses the whole model and assembles the full dataflow and test what's in the `transform` array, but that doesn't feel like the right approach. Open to ideas/suggestions here. 

Re: your suggested solutions, option (1) won't work because the existing `fromEncoding` logic expects `TypedFieldDefs` -- selections only hold field and channel names as strings to simplify assembly. I'm happy to merge into a single `makeImplicitFromEncodingAndSelection` such that only a single `implicit` object is populated and passed to `makeWithAncestors` if we prefer that. I chose the current approach because I thought that better separated concerns. 

Let me know what you'd prefer.

**Comment by arvind** [comment]
Thanks, I'd forgotten to send a PR for updating the `vlSelectionTest` function to no longer use a field accessor function. We should see the expected behavior with vega/vega#2002.

File: src/compile/data/parse.ts (hunk 1 above)
Comment (arvind) [reply src/compile/data/parse.ts]:
```json
{
  "$schema": "https://vega.github.io/schema/vega-lite/v3.json",
  "selection": {
    "grid": {
      "type": "multi", "fields": ["nested.a"]
    }
  },
  "data": {
    "values": [
      {"nested":{ "a": "1", "b": 28}},
      {"nested":{ "a": "2", "b": 55}},
      {"nested":{ "a": "3", "b": 43}},
      {"nested":{ "a": "4", "b": 91}},
      {"nested":{ "a": "5", "b": 81}},
      {"nested":{ "a": "6", "b": 53}},
      {"nested":{ "a": "7", "b": 19}},
      {"nested":{ "a": "8", "b": 87}},     
      {"nested":{ "a": "8", "b": 52}}
    ]
  },
  "mark": "point",
  "encoding": {
    "y": {
      "field": "nested.b",
      "type": "quantitative"
    },
    "x": {
      "field": "nested.b",
      "type": "quantitative"
    },
    "color": {
      "condition": {"selection": "grid", "value": "red"}
    }
  }
}
```

does not yield any duplicate flattening (though it should, were it an issue I think?).

Comment (domoritz) [reply src/compile/data/parse.ts]: Which field would you expect to be flattened twice?

I can take care of avoiding duplicate flattening since I am more familiar with the dataflow stuff.

**Comment by domoritz** [comment]
Is it necessary to update Vega or should Vega-Lite generate different spec as I suggested above?

File: src/compile/data/parse.ts (hunk 1 above)
Comment (arvind) [reply src/compile/data/parse.ts]: Sorry, I think we did a simultaneous update. In the updated spec above, the selection is projected over `nested.b` which is also used in `encoding`. We would expect to see duplicates, but we don't. I think this was your original concern in https://github.com/vega/vega-lite/pull/5351#discussion_r321986174 but perhaps I'm misunderstanding?

**Comment by arvind** [comment]
We should update Vega to keep our logic consistent. Otherwise, we introduce more complexity of needing to remember when we're referring to flattened fields, and when we're referring to nested fields. I'd rather not need to remember how to coordinate that, and just reference flattened fields always.

**Comment by arvind** [comment]
Oh I just noticed that Vega-Lite outputs `nested\\.b` for field refs elsewhere. Which function should I be calling to output the escaped version instead?

**Comment by domoritz** [comment]
We have to remember already since when we access a `field` in Vega and use a `.`, Vega interprets it as a nested access. But if we use `.` to write a field with `as`, the field is flattened and `.` becomes part of the name of the field.

**Comment by domoritz** [comment]
@arvind Please have a look at afc6337 and merge if you think it looks good.

**Comment by arvind** [comment]
That’s a nice solution! Thanks @domoritz!
