### PR TITLE
fix: merge legends on explicit color scale/range/domain

### LINKED ISSUE #9599: Custom line color scheme + strokeDash renders 2 legends
Possibly related: #5996 (and the other linked issues there)

## Bug Description

Note: the below schema were generated using altair so I've not looked  too closely at them.

When rendering a line chart with a strokeDash and color with derived domains, a single legend with colored dashed lines is rendered, so scheme:

````
{
  "config": {"view": {"continuousWidth": 300, "continuousHeight": 300}},
  "data": {"name": "data-8a876a72fa2765956ff2e0a4fa9c735a"},
  "mark": {"type": "line"},
  "encoding": {
    "color": {
      "field": "kind",
      "scale": {"scheme": "lightgreyred"},
      "type": "nominal"
    },
    "strokeDash": {"field": "kind", "type": "nominal"},
    "x": {"field": "x", "type": "quantitative"},
    "y": {"field": "y", "type": "quantitative"}
  },
  "resolve": {"scale": {"color": "independent", "strokeDash": "independent"}},
  "$schema": "https://vega.github.io/schema/vega-lite/v5.20.1.json",
  "datasets": {
    "data-8a876a72fa2765956ff2e0a4fa9c735a": [
      {"x": 0, "y": 0, "kind": "a"},
      {"x": 1, "y": 1, "kind": "a"},
      {"x": 2, "y": 2, "kind": "a"},
      {"x": 3, "y": 3, "kind": "a"},
      {"x": 0, "y": 3, "kind": "b"},
      {"x": 1, "y": 2, "kind": "b"},
      {"x": 2, "y": 1, "kind": "b"},
      {"x": 3, "y": 0, "kind": "b"}
    ]
  }
}

````

results in a legend:

Image

However setting an explicit color scale/range/domain splits this into 2 separate legends, so:

````
{
  "config": {"view": {"continuousWidth": 300, "continuousHeight": 300}},
  "data": {"name": "data-8a876a72fa2765956ff2e0a4fa9c735a"},
  "mark": {"type": "line"},
  "encoding": {
    "color": {
      "field": "kind",
      "scale": {"domain": ["a", "b"], "range": ["red", "blue"]},
      "type": "nominal"
    },
    "strokeDash": {"field": "kind", "type": "nominal"},
    "x": {"field": "x", "type": "quantitative"},
    "y": {"field": "y", "type": "quantitative"}
  },
  "resolve": {"scale": {"color": "independent", "strokeDash": "independent"}},
  "$schema": "https://vega.github.io/schema/vega-lite/v5.20.1.json",
  "datasets": {
    "data-8a876a72fa2765956ff2e0a4fa9c735a": [
      {"x": 0, "y": 0, "kind": "a"},
      {"x": 1, "y": 1, "kind": "a"},
      {"x": 2, "y": 2, "kind": "a"},
      {"x": 3, "y": 3, "kind": "a"},
      {"x": 0, "y": 3, "kind": "b"},
      {"x": 1, "y": 2, "kind": "b"},
      {"x": 2, "y": 1, "kind": "b"},
      {"x": 3, "y": 0, "kind": "b"}
    ]
  }
}
````

results in

Image

Which was incredibly confusing because I added the strokeDash second but all other examples gave the expected legend behaviour.

<details>
  <summary><h2>Checklist</h2></summary>

- [x] I checked for duplicate issues.
</details>

### PR DESCRIPTION
**Pull request by yuvvantalreja**
Fixes #9599, #5996, #3797

## PR Description

The current legend merging logic uses a naive domain hash approach that fails to merge legends encoding the same field when they have different domain representations. For example:

Scale A: `{"field": "kind", "scale": {"domain": ["a", "b"]}}` (explicit domain)
Scale B: `{"field": "kind"}` (inferred domain)
These produce different domain hashes even though they encode the same field, resulting in separate legends when they should be merged.

### Key Changes:

- Refactored legend grouping to prioritize field-based grouping over domain-based grouping (`getFieldKeyForChannel()` recursively detects fields across model hierarchies)
- Only allows cross-channel merging for explicitly specified fields
- Falls back to domain-based grouping when field detection fails

### CODE REVIEW

File: src/compile/legend/assemble.ts [hunk 1]
```diff
@@ -20,29 +26,178 @@ function setLegendEncode(
   legend.encode[part].update[vgProp] = vgRef;
 }
 
+/**
+ * Determines the underlying field name for a given scale channel within a model hierarchy.
+ * @param model - The model to search for the field definition
+ * @param channel - The scale channel (e.g., 'color', 'size', 'shape') to find the field for
+ * @returns The field name if found; otherwise undefined
+ */
+function getFieldKeyForChannel(model: Model, channel: ScaleChannel): string | undefined {
```
Comment (domoritz) [inline src/compile/legend/assemble.ts]: I'm trying to remember whether we really need this. The model does have the fields already and I think we may already populate the field in the model. Can you check that we really don't have it yet? And if so, this method maybe should be in the model.
