### PR TITLE
[BugFix] Fix config precedence

### LINKED ISSUE #4745: Mark shape value is overridden by config shape value
When `config.point.shape=circle` and `mark.shape=square`, a circle is rendered.

```json
{
  "$schema": "https://vega.github.io/schema/vega-lite/v3.json",
  "config": { "point": { "shape": "circle" } },
  "mark": {"type": "point", "shape": "square", "size": 500},
  "data": { "values": [ [null] ] }
}
```

Contrast that with text, where `config.text.text=X` and `mark.text=Y` will (correctly) display "Y".

```json
{
  "$schema": "https://vega.github.io/schema/vega-lite/v3.json",
  "config": { "text": { "text": "X" } },
  "mark": {"type": "text", "text": "Y"},
  "data": { "values": [ [null] ] }
}
```

### PR DESCRIPTION
**Pull request by kanitw**
Fix #4745

### CODE REVIEW

File: src/compile/mark/tick.ts [hunk 1]
```diff
@@ -36,6 +36,7 @@ function defaultSize(model: UnitModel): number {
   const orient = markDef.orient;
   const scale = model.getScaleComponent(orient === 'horizontal' ? 'x' : 'y');
 
+  // TODO:
```
Comment (domoritz) [inline src/compile/mark/tick.ts]: Todo: write a comment
