### PR TITLE
fix: make labelFlush work when labelAngle is set

### LINKED ISSUE #6341: Setting label angle removes label flush
Setting the label angle removes label flush. We could say that this is by design but it's a bit jarring. Not sure whether this is a regression either. 

[Open the Chart in the Vega Editor](https://vega.github.io/editor/#/url/vega-lite/N4KABGBEAkDODGALApgWwIaQFxUQFzwAdYsB6UgN2QHN0A6agSz0QFcAjOxge1IRQyUa6ALQAbZskoAWOgCtY3AHaQANOCgATZAgBOjQnh4qckAIJhYjVITHIw7dLrBIneMAHdmiMGnbJNbU0wTXQ8ejUNSFDw7DBQCAhICnQxVh04gG0NRPjITFMzNSh2OIAmAA4AX1U8gqgAIWLIUpwAVjaaurjIAGFm1rBpAGYanMTgfJ6AEQG4gE4ARi7J+sgAUTmcCuXa1Z6AMS2wNtH1XIh90wBxY8X5lanTAAljioB2R7WASWO2sqq4wAuhoxkkMLoANY9Ry6SJJZBKeDcTSMJTUOIJRKQAAemMgADNGMgxJoYc08ABPQjIHoAR1Y6CURnCRiozXQOMYsHxYnQ-jEZnRdjiAAYqoCIIDAUA)

### PR DESCRIPTION
**Pull request by kanitw**
fix #6341

### CODE REVIEW

File: src/compile/axis/properties.ts [hunk 1]
```diff
@@ -179,7 +184,9 @@ export function defaultLabelBaseline(angle: number, axisOrient: AxisOrient, chan
         : 'top';
     } else {
       return angle <= 45 || 315 <= angle || (135 <= angle && angle <= 225)
-        ? 'middle'
+        ? alwaysIncludeMiddle
```
Comment (kanitw) [inline src/compile/axis/properties.ts:187]: This nesting is ugly, but it will be fixed in the orient signal PR anyway.
