### PR TITLE
fix: preserve node order in swapWithParent

### LINKED ISSUE #4680: Error: Undefined data set name: "scale_concat_1_child_main"
I am trying to `hconcat` a faceted graph over two fields with a summary graph (summing across one of the fields). If I have `color` set in the first chart, then I get the error listed in the title (`Undefined data set name: "scale_concat_1_child_main"`).

[Broken code in Vega Editor](https://vega.github.io/editor/#/url/vega-lite/N4KABBYEQCQM4GMAWBTAtgQygLmkgLvgA5zYD0ZAbigOYYB0NAlvkgK4BG9TA9mYqkxVaGALQAbFiioBmegCs4PAHZQANOEhQAJhnxZcoSMeiUM4tijg4wAbU0mTRxy4hQEARhtQAggCc6OgD1B1cTdwAmb39AjGCNMJcoNDZvCNEADhDExygAdyZlAH1kDGUEFBsABnoIhJzjKCJq+iqqgFYIgE4ZDy6ugHYBjIAWGS62kfqGt3wATyJK3CgacR4Oc2yZtwQ2NCLm3BqRntG2qu6RgDYRj2720NcAX2mw5233L2WYjCCaLY+CCiywAQmCATNkqllhF6O1RAM4RCGvlCiUkGUKi0Iu1XijDmAam0rr0hhlxu0ru0RhkBuM8TkoPNFt5VutNgzEu49gcWrcMhEPLcZFcPFVye06Y8XC9pY53pDPN4wSDkYygdEAr84v9OWEod4RqIrmquQViqVyktCfRxv17Q7HQM9a4mi02u1+qKZBEMlTxQMIlcXUlmdaVmsNuJTfrdvsCTV2hkxRNRjILh0MgK5SZZQ0FSilaDwSHchri6rS+EUmk4QikVXGub0ZjrTUcY2tAnWh4BmMBlUPJ1JT72lUZDJO7MFuG2VGY6647yjnDB0O6X7KVmRiMBjnjE8cwBdUJ5rT4PxlOAAMx4fjQNnsrgLSXkPEKvxofhE+GtT+2YAvh8PAEskKBlAujLXkwKDiNo3hLs0U7hBg1jLJ4RQYJQNAlDyzT7jKBEQEeVYrH4PBsEQHBzI+RHhEqdEns8oQkaEUBIAgKgIHotHPnRUDXhgFT4DYQH6uReSiXRrrQbB8HoV4yGNGG3h3toH7RtJkBnoCPAWGgqiGFpuSyXBCFREp54zqpfjqcomzGWAh4NDp+pwIsCBSQB0CYH4ADWXneVZLLLBsfhQI5rkoig5Q8HZ-xGUFWgAB6BUljSmfJPmpJZuQqcsakaRF6VObl0A0YlJVaJl3hIY5rr5dAACObBlPgLB6Ew1DFelUUAe4el3mlVUCTBZnoXhkEfI1UAtW1HXtd19XaZFdHOTKepiRlQkoCJlUfBJw3eaNckIYpy3TiF0CFfZmneetiR9bk7koJ5+2Qr5AXvcdM1hT12xPfqMWcfFR39al33pSd43ZVNkIzTdDklYDKIVYBF0oTQX4-uGaDgaoZUZWNWVuoTwXhnNyjtfoi2VBjKPqoN4WQ0lUCft+dC-t4eMQWTbg1QpmHYbh8ZwyiM2U9TnVLcjq0uTmD1gCeTxAA)

[Working code in Vega Editor](https://vega.github.io/editor/#/url/vega-lite/N4KABBYEQCQM4GMAWBTAtgQygLmkgLvgA5zYD0ZAbigOYYB0NAlvkgK4BG9TA9mYqkxVaGALQAbFiioBmegCs4PAHZQANOEhQAJhnxZcoSMeiUM4tijg4wAbU0mTRxy4hQEARhtQAggCc6OgD1B1cTdwAmb39AjGCNMJcoNDZvCNEADhDExygAdyZlAH1kDGUEFBsABnoIhJzjKCJq+iqqgFYIgE4ZDy6ugHYBjIAWGS62kfqGt3wATyJK3CgacR4Oc2yZtwQ2NCLm3BqRntG2qu6RgDYRj2720NcAX2mw5233L2WYjCCaLY+CCiywAQmCATNkqllhF6O1RAM4RCGvlCiUkGUKi0Iu1XijDmAam0rr0hhlxu0ru0RhkBuM8TkoPNFt5VutNgzEu49gcWrcMhEPLcZFcPFVye06Y8XC9pY53pDPN4wSDkYygdEAr84v9OWEod4RqIrmquQViqVyktCfRxv17Q7HQM9a4mi02u1+qKZBEMlTxQMIlcXUlmdaVmsNuJTfrdvsCTV2hkxRNRjILh0MgK5SZZQ0FSilaDwSHchri6rS+EUmk4QikVXGub0ZjrTUcY2tAnWh4BmMBlUPJ1JT72lUZDJO7MFuG2VGY6647yjnDB0O6X7KVmRiMBjnjE8cwBdUJ5rT4PxlOAAMx4fjQNnsrgLSXkPEKvxofhE+GtT+2YAvh8PAEskKBlAujLXkwKDiNo3hLs0U7hBg1jLJ4RQYJQNAlDyzT7jKBEQEeVYrH4PBsEQHBzI+RHhEqdEns8oQkaEUBIAgKgIHotHPnRUDXhgFT4DYQH6uReSiXRrrQbB8HoV4yGNGG3h3toH7RtJkBnoCPAWGgqiGFpuSyXBCFREp54zqpfjqcomzGWAh4NDp+pwIsCBSQB0CYH4ADWXneVZLLLBsfhQI5rkoig5Q8HZ-xGUFWgAB6BUljSmfJPmpJZuQqcsakaRF6VObl0A0YlJVaJl3hIY5rr5dAACObBlPgLB6Ew1DFelzkAX1iQDbmepiRlQkoCJlUfBJaVBQJMFmQpkFco1UCFfZmneUNzyke5KCeVNkK+QFh3eUy1mhXEPXbFFjIxZx8WzWdqWnel81yd4NZlcpF3QOtDklbdHwVYB9VJJ+350L+n3gao33VQtWVuvD04hc1rXKO1+jtd1YMQEDip6XeT1vRDP7hmgsPLZCNUKZh2G4fG1MoqtLVtR1OOVHjTmRXR23aSxIBPEAA)

```json
{
    "$schema": "https://vega.github.io/schema/vega-lite/v3.json",
    "data": {
        "values": [
            {
                "c1": "Argagarg",
                "c2": "Argagarg",
                "mu": "2-8",
                "win_chance": 0.2,
                "p": 0.005293199778439004,
                "type": "global",
                "cum_p": 0.49384000294641295
            },
            {
                "c1": "Argagarg",
                "c2": "BBB",
                "mu": "2.5-7.5",
                "win_chance": 0.25,
                "p": 0.006317783956548739,
                "type": "global",
                "cum_p": 0.4182141361083573
            },
            {
                "c1": "BBB",
                "c2": "Argagarg",
                "mu": "4-6",
                "win_chance": 0.39999999999999997,
                "p": 0.00599613286508726,
                "type": "global",
                "cum_p": 0.5810908430205882
            },
            {
                "c1": "BBB",
                "c2": "BBB",
                "mu": "2.5-7.5",
                "win_chance": 0.25,
                "p": 0.017437015257325033,
                "type": "global",
                "cum_p": 0.5011573865688447
            }
        ]
    },
    "transform": [
        {
            "joinaggregate": [
                {
                    "op": "mean",
                    "field": "cum_p",
                    "as": "c1_avg_cum_p"
                }
            ],
            "groupby": [
                "c1"
            ]
        }
    ],
    "hconcat": [
        {
            "facet": {
                "row": {
                    "field": "c1",
                    "type": "ordinal"
                },
                "column": {
                    "field": "c2",
                    "type": "ordinal"
                }
            },
            "spec": {
                "mark": {
                    "type": "bar"
                },
                "encoding": {
                    "x": {
                        "field": "mu",
                        "type": "ordinal"
                    },
                    "y": {
                        "field": "p",
                        "type": "quantitative"
                    },
                    "color": { // If I remove this object, the graph works
                        "field": "cum_p",
                        "type": "quantitative"
                    }
                }
            }
        },
        {
            "facet": {
                "row": {
                    "field": "c1",
                    "type": "ordinal"
                }
            },
            "spec": {
                "mark": {
                    "type": "bar"
                },
                "encoding": {
                    "x": {
                        "field": "mu",
                        "type": "ordinal"
                    },
                    "y": {
                        "aggregate": "mean",
                        "field": "p",
                        "type": "quantitative"
                    },
                    "color": {
                        "aggregate": "mean",
                        "field": "c1_avg_cum_p",
                        "type": "quantitative"
                    }
                }
            }
        }
    ]
}
```

### PR DESCRIPTION
**Pull request by RobinL**
This PR closes #4680 and #5475.  It helps with part of #5261.

The root cause of the problem is within the [moveFacetDown map](https://github.com/vega/vega-lite/blob/ac00c92b01aa702be251d89d463f2df53e612e8b/src/compile/data/optimize.ts#L98). 

The problem occurs because the `swapWithParent` method does not preserve the order of branches in the tree, so the main [map](https://github.com/vega/vega-lite/blob/ac00c92b01aa702be251d89d463f2df53e612e8b/src/compile/data/optimize.ts#L98) iterates incorrectly.  It expects to be able to iterate over each branch in turn, but when the order changes, this fails.

I have used the following spec to find the bug.

<details>
<summary>Example buggy spec</summary>

```
{
  "$schema": "https://vega.github.io/schema/vega-lite/v5.json",
  "data": {
    "values": [
      { "metric_1": 10, "metric_2": 1, "y_value": 0.2, "row_group": false },
      { "metric_1": 11, "metric_2": 1, "y_value": 0.3, "row_group": false },
      { "metric_1": 12, "metric_2": 2, "y_value": 0.1, "row_group": false },
      { "metric_1": 13, "metric_2": 2, "y_value": 0.8, "row_group": false },
      { "metric_1": 12, "metric_2": 2, "y_value": 0.7, "row_group": true },
      { "metric_1": 13, "metric_2": 3, "y_value": 0.2, "row_group": true },
      { "metric_1": 14, "metric_2": 3, "y_value": 0.4, "row_group": true },
      { "metric_1": 15, "metric_2": 4, "y_value": 0.9, "row_group": true } ]
  },
  "hconcat": [
    {
      "encoding": {
        "row": {
          "field": "row_group",
          "type": "nominal"
        },
        "x": {
          "field": "metric_2",
          "type": "quantitative"
        },
        "y": {
          "field": "y_value",
          "title": null,
          "type": "quantitative"
        }
      },
      "mark": "bar"
    },
    {
      "encoding": {
        "row": {
          "field": "row_group",
          "type": "nominal"
        },
        "x": {
          "field": "metric_1",
          "type": "quantitative"
        },
        "y": {
          "field": "y_value",
          "title": null,
          "type": "quantitative"
        }
      },
      "mark": "bar"
    }
  ]
}

```

</details>

To be more specific, with this example spec, in `optimize.ts` immediately prior to [the `moveFacetDown` map](https://github.com/vega/vega-lite/blob/ac00c92b01aa702be251d89d463f2df53e612e8b/src/compile/data/optimize.ts#L98), `data.sources` is a symmetrical tree like:

```
Source
├── OutputNode
│   └── FacetNode
│       └── FilterInvalidNode
│           └── OutputNode
└── OutputNode
    └── FacetNode
        └── FilterInvalidNode
            └── OutputNode
```

However, following the map, the data structure has become asymmetrical.  This is because `swapWithParent` does not preserve the order of the children.  But we're iterating recursively over these children, so the recursive map becomes asymetrical.  

The order fails to be preserved because when you remove a child and then re-add it [here](https://github.com/vega/vega-lite/blob/ac00c92b01aa702be251d89d463f2df53e612e8b/src/compile/data/dataflow.ts#L119), its position in the array is not preserved.

I have tested this against the following specs which are reported as broken in #4680, with the following outputs, which look correct to me.

Grateful for any feedback on the fix.   I've run tests locally, but I'm not sure I understand [this] about adding a `GH_PAT`.  Is that saying that, in my fork, I need to add a secret containing a personal access token that has only `public_repo` permissions?  I didn't want to do that without checking, because of potential security implications.

Specs:

<details>
<summary>My example used to bugfix</summary>

```
{
  "$schema": "https://vega.github.io/schema/vega-lite/v5.json",
  "data": {
    "values": [
      { "metric_1": 10, "metric_2": 1, "y_value": 0.2, "row_group": false },
      { "metric_1": 11, "metric_2": 1, "y_value": 0.3, "row_group": false },
      { "metric_1": 12, "metric_2": 2, "y_value": 0.1, "row_group": false },
      { "metric_1": 13, "metric_2": 2, "y_value": 0.8, "row_group": false },
      { "metric_1": 12, "metric_2": 2, "y_value": 0.7, "row_group": true },
      { "metric_1": 13, "metric_2": 3, "y_value": 0.2, "row_group": true },
      { "metric_1": 14, "metric_2": 3, "y_value": 0.4, "row_group": true },
      { "metric_1": 15, "metric_2": 4, "y_value": 0.9, "row_group": true } ]
  },
  "hconcat": [
    {
      "encoding": {
        "row": {
          "field": "row_group",
          "type": "nominal"
        },
        "x": {
          "field": "metric_2",
          "type": "quantitative"
        },
        "y": {
          "field": "y_value",
          "title": null,
          "type": "quantitative"
        }
      },
      "mark": "bar"
    },
    {
      "encoding": {
        "row": {
          "field": "row_group",
          "type": "nominal"
        },
        "x": {
          "field": "metric_1",
          "type": "quantitative"
        },
        "y": {
          "field": "y_value",
          "title": null,
          "type": "quantitative"
        }
      },
      "mark": "bar"
    }
  ]
}
```

robin_example
</details>

<details>
<summary>cpennington example</summary>

```
{
  "$schema": "https://vega.github.io/schema/vega-lite/v3.json",
  "data": {
    "values": [
      {
        "c1": "Argagarg",
        "c2": "Argagarg",
        "mu": "2-8",
        "win_chance": 0.2,
        "p": 0.005293199778439004,
        "type": "global",
        "cum_p": 0.49384000294641295
      },
      {
        "c1": "Argagarg",
        "c2": "BBB",
        "mu": "2.5-7.5",
        "win_chance": 0.25,
        "p": 0.006317783956548739,
        "type": "global",
        "cum_p": 0.4182141361083573
      },
      {
        "c1": "BBB",
        "c2": "Argagarg",
        "mu": "4-6",
        "win_chance": 0.39999999999999997,
        "p": 0.00599613286508726,
        "type": "global",
        "cum_p": 0.5810908430205882
      },
      {
        "c1": "BBB",
        "c2": "BBB",
        "mu": "2.5-7.5",
        "win_chance": 0.25,
        "p": 0.017437015257325033,
        "type": "global",
        "cum_p": 0.5011573865688447
      }
    ]
  },
  "transform": [
    {
      "joinaggregate": [
        {
          "op": "mean",
          "field": "cum_p",
          "as": "c1_avg_cum_p"
        }
      ],
      "groupby": [
        "c1"
      ]
    }
  ],
  "hconcat": [
    {
      "facet": {
        "row": {
          "field": "c1",
          "type": "ordinal"
        },
        "column": {
          "field": "c2",
          "type": "ordinal"
        }
      },
      "spec": {
        "mark": {
          "type": "bar"
        },
        "encoding": {
          "x": {
            "field": "mu",
            "type": "ordinal"
          },
          "y": {
            "field": "p",
            "type": "quantitative"
          },
          "color": {
            "field": "cum_p",
            "type": "quantitative"
          }
        }
      }
    },
    {
      "facet": {
        "row": {
          "field": "c1",
          "type": "ordinal"
        }
      },
      "spec": {
        "mark": {
          "type": "bar"
        },
        "encoding": {
          "x": {
            "field": "mu",
            "type": "ordinal"
          },
          "y": {
            "aggregate": "mean",
            "field": "p",
            "type": "quantitative"
          },
          "color": {
            "aggregate": "mean",
            "field": "c1_avg_cum_p",
            "type": "quantitative"
          }
        }
      }
    }
  ]
}
```

cpennington_example

</details>

<details>
<summary>sh4pe example</summary>

```
{
  "$schema": "https://vega.github.io/schema/vega-lite/v4.json",
  "data": {
    "values": [
      {
        "a": 0.1,
        "x": -5,
        "b": 0.1,
        "date": "2019-12-01T00:00:00"
      },
      {
        "a": 0.1,
        "x": 5,
        "b": 0.2,
        "date": "2019-12-01T00:00:00"
      },
      {
        "a": 0.1,
        "x": -55,
        "b": 0.1,
        "date": "2019-12-03T00:00:00"
      },
      {
        "a": 0,
        "x": -45,
        "b": 0.1,
        "date": "2019-12-03T00:00:00"
      }
    ]
  },
  "hconcat": [
    {
      "facet": {
        "column": {
          "field": "date",
          "type": "ordinal"
        }
      },
      "spec": {
        "encoding": {
          "x": {
            "field": "x",
            "type": "quantitative"
          },
          "y": {
            "field": "a",
            "type": "quantitative"
          }
        },
        "mark": "bar"
      }
    },
    {
      "facet": {
        "column": {
          "field": "date",
          "type": "ordinal"
        }
      },
      "spec": {
        "encoding": {
          "x": {
            "field": "x",
            "type": "quantitative"
          },
          "y": {
            "field": "b",
            "type": "quantitative"
          }
        },
        "mark": "bar"
      }
    }
  ]
}
```

sh4pe_example

</details>

<details>
<summary>Isue 5475 example</summary>

```
{
  "$schema": "https://vega.github.io/schema/vega-lite/v4.json",
  "data": {"values": [{"a": "A", "b": 28}, {"a": "B", "b": 55}]},
  "vconcat": [
    {
      "title": "Title for first row",
      "facet": {"field": "a", "type": "ordinal"},
      "spec": {
        "mark": "bar",
        "encoding": {"y": {"field": "b", "type": "quantitative"}}
      }
    },
    {
      "title": "Title for second row",
      "facet": {"field": "a", "type": "ordinal"},
      "spec": {
        "mark": "bar",
        "encoding": {"y": {"field": "b", "type": "quantitative"}}
      }
    }
  ]
}
```

5475_example

</details>

<details>
<summary>Isue 5261 example</summary>

```
{
  "$schema": "https://vega.github.io/schema/vega-lite/v3.json",
  "data": {"url": "data/cars.json"},
  "vconcat": [
    {
      "facet": {"field": "Origin", "type": "nominal"},
      "spec": {
        "mark": "point",
        "encoding": {
          "x": {"field": "Horsepower", "type": "quantitative"},
          "y": {"field": "Miles_per_Gallon", "type": "quantitative"}
        }
      }
    },
    {
      "facet": {"field": "Origin", "type": "nominal"},
      "spec": {
        "mark": "tick",
        "encoding": {
          "x": {"field": "Horsepower", "type": "quantitative"}
        }
      }
    }
  ]
}
```

5261_example

</details>

### CODE REVIEW

File: src/compile/data/dataflow.ts [hunk 1]
```diff
@@ -116,11 +116,14 @@ export abstract class DataFlowNode {
     // remove old links
     this._children = []; // equivalent to removing every child link one by one
     parent.removeChild(this);
-    parent.parent.removeChild(parent);
+    const loc = parent.parent.removeChild(parent);
 
     // swap two nodes
```
Comment (domoritz) [inline src/compile/data/dataflow.ts:121]:
```suggestion
    // swap two nodes but maintain order in children
```

File: src/compile/data/dataflow.ts [hunk 2]
```diff
@@ -116,11 +116,14 @@ export abstract class DataFlowNode {
...
-    this.parent = newParent;
-    parent.parent = this;
+    this._parent = newParent;
+    newParent.addChild(this, loc);
+
+    parent._parent = this;
+    this.addChild(parent, loc);
```
Comment (domoritz) [inline src/compile/data/dataflow.ts:126]: I don't get this one. Isn't `loc` the location in `parent.parent`?

```suggestion
    parent.parent = this;
```

**Review by domoritz — COMMENTED** [review]
One comment. Other than that, looks great. 

Thanks for your patience with my review.

File: src/compile/data/dataflow.ts (hunk 2 above)
Comment (domoritz) [reply src/compile/data/dataflow.ts:126]: I tested with this change and it seems like your examples are still correct.

Comment (RobinL) [reply src/compile/data/dataflow.ts:126]: Thanks so much!  Yes, happy with your suggestion - that was just me not having a great grasp of some of the internals.

**Comment by RobinL** [comment]
Thanks.  Happy with your suggestion. That was just my lack of understanding of the internals, your version is clearer. 

I haven't clicked 'commit suggestion' in the GitHub UI just because I don't want to mess up the house style for commit messages.  Happy for you to commit them, or I can batch them into a commit.  Would a commit message of `fix: preserve node order in swapwithparents` (same as my original commit) be suitable?

**Comment by domoritz** [comment]
We will squash the commits anyway so the individual commit messages are not as critical.
