### PR TITLE
fix: smoothen `value` gradient for var param -> point selection

### LINKED ISSUE #7206: Smooth the "value"  for selection

### PR DESCRIPTION
**Pull request by arvind**
Fixes #7206

### CODE REVIEW

File: src/compile/selection/project.ts [hunk 1]
```diff
@@ -161,7 +166,9 @@ const project: SelectionCompiler = {
 
     if (init) {
       selCmpt.init = (init as any).map((v: SelectionInitMapping | SelectionInitIntervalMapping) => {
-        return proj.items.map(p => (v[p.channel] !== undefined ? v[p.channel] : v[p.field]));
+        // selections can be initialized either with a full object that maps projections to values
```
Comment (domoritz) [inline src/compile/selection/project.ts:169]:
```suggestion
        // Selections can be initialized either with a full object that maps projections to values
```

**Review by domoritz — APPROVED** [review]
