### PR TITLE
Fix stack 

### LINKED ISSUE #683: Revising stack syntaxes
- [x] 1) __Revise if we should add “-“ to stack’s sort order__

We automatically  add `’-‘` to the output Vega’s `sortby` property of `stack` transform to make legends consistent with stack order for vertical stacked bar chart.

vega_editor

However, this might not make sense for horizontal stacked bar.

Should we only add `’-'` for vertical stacked bar chart?

Also, if a field’s `sort` is `’descending’`, we might need to revert the `'-‘` appended. 

----

- [ ] 2) __Do we only allow stack if `aggregate` is `sum` ?__
Stack of `mean`, `median`, `min`, `max` certainly do not make sense.   
What shall we do when people specify stack of mean / median?  

- Do we throw error/warning?
- Do we should layered bar chart for these by default?

-----

- [ ] 3) __Should stack be a part of `x`,`y` instead of `color`/`detail`?__

`stack.offset` actually applies to the quantitative encoding channel (either `x` or `y`) rather than `color`/`detail`.

However, stack is only applied when either `color` or `detail` is specified. 

——

Any thoughts on these 3 issues?

### PR DESCRIPTION
**Pull request by kanitw**
__Please merge #764 first !  (See [Branch Specific Diff](https://github.com/uwdata/vega-lite/compare/kw/model...kw/stack))__

Fixes #683 

## syntax 
- move `stack` property from `color`/`detail` to `config`
  - make `stack` config supports an array of fields. 

## output 
- make stack uses descending by default 

## API 
- update `vl.spec.isStack()`

## Internal
- add StackDef interface
- calculate `_stack` only once in model 

## Docs
- Add docs for stack in `Config.md` 
——

### CODE REVIEW

File: src/compiler/data.ts [hunk 1]
```diff
@@ -18,7 +19,7 @@ import {NOMINAL, ORDINAL, QUANTITATIVE, TEMPORAL} from '../type';
  *                 If the encoding contains aggregate value, this will also create
  *                 aggregate table as well.
  */
-export default function(model: Model) {
+export function def(model: Model) {
```
Comment (domoritz) [inline src/compiler/data.ts]: What is the reason for this?

File: src/compiler/data.ts [hunk 2]
```diff
@@ -18,7 +19,7 @@ import {NOMINAL, ORDINAL, QUANTITATIVE, TEMPORAL} from '../type';
...
   var def = [source.def(model)];
```
Comment (domoritz) [inline src/compiler/data.ts]: def used again

File: src/compiler/data.ts [hunk 3]
```diff
@@ -254,9 +255,9 @@ export namespace stack {
   /**
    * Add stacked data source, for feeding the shared scale.
    */
-  export function def(model: Model, stackCfg):VgData {
-    var dim = stackCfg.groupby;
-    var val = stackCfg.value;
+  export function def(model: Model, stackDef: StackDef):VgData {
```
Comment (domoritz) [inline src/compiler/data.ts]: and again

File: src/compiler/data.ts (hunk 2 above)
Comment (kanitw) [inline src/compiler/data.ts]: good catch ...

File: src/compiler/data.ts (hunk 1 above)
Comment (kanitw) [inline src/compiler/data.ts]: We shouldn't use `default` because it creates weird `.default` when you do require in the compiled javascript.  But I do agree that `def` isn't the right way to name this.

Comment (domoritz) [inline src/compiler/data.ts]: I disagree that default is weird. It is in the es6 standard https://people.mozilla.org/~jorendorff/es6-draft.html#sec-exports. I think we shouldn't change this for the wrong reasons.

Comment (kanitw) [inline src/compiler/data.ts]: While default is in the ES6 standard, that doesn't mean that it is a good practice.   

By using default, that means you always create alias with arbitrary names every time you import and there is no mechanism for enforcing that you will name the alias similarly.  Therefore, unless there is a good reason.  Providing method name such as `compileData()` and do `import {compileData} from './data.ts'` is a much better way.   On that note, I'm creating a PR to change all confusing `def()`, `defs()` to `compileXXX()` ... will send you when I'm done.

Comment (domoritz) [inline src/compiler/data.ts]: I still disagree that `default` is always a bad idea but agree that we should use `compileXXX()`.

Comment (kanitw) [inline src/compiler/data.ts]: I'm not saying it is __always__ bad, but avoid it

>  unless there is a good reason

File: src/compiler/data.ts (hunk 3 above)
Comment (kanitw) [inline src/compiler/data.ts]: This doesn't create redundant variable name though.  

That said, I don't like the `stackDef` name.   But can't think of a better name.  
It combines some properties and config in the same object so I can't call it `StackConfig`.  

Any suggestion?

File: src/compiler/data.ts (hunk 1 above)
Comment (domoritz) [inline src/compiler/data.ts]: Fair enough. Do you think it is sensible to say that we only use default if 1) there is only one function exported from a module 2) that function pretty much resembles what you would expect the module to do.

File: src/compiler/data.ts (hunk 3 above)
Comment (domoritz) [inline src/compiler/data.ts]: stackProps maybe

Comment (kanitw) [inline src/compiler/data.ts]: or stackModel? lol
