### PR TITLE
fix: remove duplicate sort index computation in faceted charts

### LINKED ISSUE #6069: Example generates two calculates
```
{
  "$schema": "https://vega.github.io/schema/vega-lite/v4.json",
  "description": "Average temperatures in Seattle, broken down by hour. Derived from [Seattle Annual Temperate](https://vega.github.io/vega/examples/annual-temperature/) example from the Vega example gallery.",
  "width": 800,
  "height": 25,
  "view": {"stroke": null},
  "title": "Seattle Annual Temperatures",
  "data": {"url": "data/seattle-temps.csv"},
  "mark": "area",
  "encoding": {
    "x": {
      "field": "date",
      "type": "temporal",
      "title": "Month",
      "axis": {"labelExpr": "timeFormat(datum.value, '%b')"}
    },
    "y": {
      "field": "temp",
      "type": "quantitative",
      "axis": {"title": null, "labels": false, "ticks": false}
    },
    "row": {
      "field": "date",
      "timeUnit": "hours",
      "type": "nominal",
      "spacing": 1,
      "title": "Hour",
      "sort": [
        6,
        7,
        8,
        9,
        10,
        11,
        12,
        13,
        14,
        15,
        16,
        17,
        18,
        19,
        20,
        21,
        22,
        23,
        0,
        1,
        2,
        3,
        4,
        5
      ],
      "header": {
        "labelAngle": 0,
        "labelPadding": 2,
        "titlePadding": -4,
        "labelAlign": "left",
        "labelExpr": "hours(datum.value) == 0 ? 'Midnight' : hours(datum.value) == 12 ? 'Noon' : timeFormat(datum.value, '%I:%M %p')"
      }
    }
  },
  "config": {"axis": {"grid": false, "domain": false}}
}
```

generates

```
        {
          "type": "formula",
          "expr": "time(datetime(0, 0, 1, hours(datum[\"date\"]), 0, 0, 0))===time(datetime(0, 0, 1, 6, 0, 0, 0)) ? 0 : time(datetime(0, 0, 1, hours(datum[\"date\"]), 0, 0, 0))===time(datetime(0, 0, 1, 7, 0, 0, 0)) ? 1 : time(datetime(0, 0, 1, hours(datum[\"date\"]), 0, 0, 0))===time(datetime(0, 0, 1, 8, 0, 0, 0)) ? 2 : time(datetime(0, 0, 1, hours(datum[\"date\"]), 0, 0, 0))===time(datetime(0, 0, 1, 9, 0, 0, 0)) ? 3 : time(datetime(0, 0, 1, hours(datum[\"date\"]), 0, 0, 0))===time(datetime(0, 0, 1, 10, 0, 0, 0)) ? 4 : time(datetime(0, 0, 1, hours(datum[\"date\"]), 0, 0, 0))===time(datetime(0, 0, 1, 11, 0, 0, 0)) ? 5 : time(datetime(0, 0, 1, hours(datum[\"date\"]), 0, 0, 0))===time(datetime(0, 0, 1, 12, 0, 0, 0)) ? 6 : time(datetime(0, 0, 1, hours(datum[\"date\"]), 0, 0, 0))===time(datetime(0, 0, 1, 13, 0, 0, 0)) ? 7 : time(datetime(0, 0, 1, hours(datum[\"date\"]), 0, 0, 0))===time(datetime(0, 0, 1, 14, 0, 0, 0)) ? 8 : time(datetime(0, 0, 1, hours(datum[\"date\"]), 0, 0, 0))===time(datetime(0, 0, 1, 15, 0, 0, 0)) ? 9 : time(datetime(0, 0, 1, hours(datum[\"date\"]), 0, 0, 0))===time(datetime(0, 0, 1, 16, 0, 0, 0)) ? 10 : time(datetime(0, 0, 1, hours(datum[\"date\"]), 0, 0, 0))===time(datetime(0, 0, 1, 17, 0, 0, 0)) ? 11 : time(datetime(0, 0, 1, hours(datum[\"date\"]), 0, 0, 0))===time(datetime(0, 0, 1, 18, 0, 0, 0)) ? 12 : time(datetime(0, 0, 1, hours(datum[\"date\"]), 0, 0, 0))===time(datetime(0, 0, 1, 19, 0, 0, 0)) ? 13 : time(datetime(0, 0, 1, hours(datum[\"date\"]), 0, 0, 0))===time(datetime(0, 0, 1, 20, 0, 0, 0)) ? 14 : time(datetime(0, 0, 1, hours(datum[\"date\"]), 0, 0, 0))===time(datetime(0, 0, 1, 21, 0, 0, 0)) ? 15 : time(datetime(0, 0, 1, hours(datum[\"date\"]), 0, 0, 0))===time(datetime(0, 0, 1, 22, 0, 0, 0)) ? 16 : time(datetime(0, 0, 1, hours(datum[\"date\"]), 0, 0, 0))===time(datetime(0, 0, 1, 23, 0, 0, 0)) ? 17 : time(datetime(0, 0, 1, hours(datum[\"date\"]), 0, 0, 0))===time(datetime(0, 0, 1, 0, 0, 0, 0)) ? 18 : time(datetime(0, 0, 1, hours(datum[\"date\"]), 0, 0, 0))===time(datetime(0, 0, 1, 1, 0, 0, 0)) ? 19 : time(datetime(0, 0, 1, hours(datum[\"date\"]), 0, 0, 0))===time(datetime(0, 0, 1, 2, 0, 0, 0)) ? 20 : time(datetime(0, 0, 1, hours(datum[\"date\"]), 0, 0, 0))===time(datetime(0, 0, 1, 3, 0, 0, 0)) ? 21 : time(datetime(0, 0, 1, hours(datum[\"date\"]), 0, 0, 0))===time(datetime(0, 0, 1, 4, 0, 0, 0)) ? 22 : time(datetime(0, 0, 1, hours(datum[\"date\"]), 0, 0, 0))===time(datetime(0, 0, 1, 5, 0, 0, 0)) ? 23 : 24",
          "as": "row_hours_date_sort_index"
        },
        {
          "type": "formula",
          "expr": "time(datetime(0, 0, 1, hours(datum[\"date\"]), 0, 0, 0))===time(datetime(0, 0, 1, 6, 0, 0, 0)) ? 0 : time(datetime(0, 0, 1, hours(datum[\"date\"]), 0, 0, 0))===time(datetime(0, 0, 1, 7, 0, 0, 0)) ? 1 : time(datetime(0, 0, 1, hours(datum[\"date\"]), 0, 0, 0))===time(datetime(0, 0, 1, 8, 0, 0, 0)) ? 2 : time(datetime(0, 0, 1, hours(datum[\"date\"]), 0, 0, 0))===time(datetime(0, 0, 1, 9, 0, 0, 0)) ? 3 : time(datetime(0, 0, 1, hours(datum[\"date\"]), 0, 0, 0))===time(datetime(0, 0, 1, 10, 0, 0, 0)) ? 4 : time(datetime(0, 0, 1, hours(datum[\"date\"]), 0, 0, 0))===time(datetime(0, 0, 1, 11, 0, 0, 0)) ? 5 : time(datetime(0, 0, 1, hours(datum[\"date\"]), 0, 0, 0))===time(datetime(0, 0, 1, 12, 0, 0, 0)) ? 6 : time(datetime(0, 0, 1, hours(datum[\"date\"]), 0, 0, 0))===time(datetime(0, 0, 1, 13, 0, 0, 0)) ? 7 : time(datetime(0, 0, 1, hours(datum[\"date\"]), 0, 0, 0))===time(datetime(0, 0, 1, 14, 0, 0, 0)) ? 8 : time(datetime(0, 0, 1, hours(datum[\"date\"]), 0, 0, 0))===time(datetime(0, 0, 1, 15, 0, 0, 0)) ? 9 : time(datetime(0, 0, 1, hours(datum[\"date\"]), 0, 0, 0))===time(datetime(0, 0, 1, 16, 0, 0, 0)) ? 10 : time(datetime(0, 0, 1, hours(datum[\"date\"]), 0, 0, 0))===time(datetime(0, 0, 1, 17, 0, 0, 0)) ? 11 : time(datetime(0, 0, 1, hours(datum[\"date\"]), 0, 0, 0))===time(datetime(0, 0, 1, 18, 0, 0, 0)) ? 12 : time(datetime(0, 0, 1, hours(datum[\"date\"]), 0, 0, 0))===time(datetime(0, 0, 1, 19, 0, 0, 0)) ? 13 : time(datetime(0, 0, 1, hours(datum[\"date\"]), 0, 0, 0))===time(datetime(0, 0, 1, 20, 0, 0, 0)) ? 14 : time(datetime(0, 0, 1, hours(datum[\"date\"]), 0, 0, 0))===time(datetime(0, 0, 1, 21, 0, 0, 0)) ? 15 : time(datetime(0, 0, 1, hours(datum[\"date\"]), 0, 0, 0))===time(datetime(0, 0, 1, 22, 0, 0, 0)) ? 16 : time(datetime(0, 0, 1, hours(datum[\"date\"]), 0, 0, 0))===time(datetime(0, 0, 1, 23, 0, 0, 0)) ? 17 : time(datetime(0, 0, 1, hours(datum[\"date\"]), 0, 0, 0))===time(datetime(0, 0, 1, 0, 0, 0, 0)) ? 18 : time(datetime(0, 0, 1, hours(datum[\"date\"]), 0, 0, 0))===time(datetime(0, 0, 1, 1, 0, 0, 0)) ? 19 : time(datetime(0, 0, 1, hours(datum[\"date\"]), 0, 0, 0))===time(datetime(0, 0, 1, 2, 0, 0, 0)) ? 20 : time(datetime(0, 0, 1, hours(datum[\"date\"]), 0, 0, 0))===time(datetime(0, 0, 1, 3, 0, 0, 0)) ? 21 : time(datetime(0, 0, 1, hours(datum[\"date\"]), 0, 0, 0))===time(datetime(0, 0, 1, 4, 0, 0, 0)) ? 22 : time(datetime(0, 0, 1, hours(datum[\"date\"]), 0, 0, 0))===time(datetime(0, 0, 1, 5, 0, 0, 0)) ? 23 : 24",
          "as": "row_hours_date_sort_index"
        }
```

### PR DESCRIPTION
**Pull request by domoritz**
Fixes #6069

### CODE REVIEW

File: src/compile/data/parse.ts [hunk 1]
```diff
@@ -396,9 +396,6 @@ export function parseData(model: Model): DataComponent {
   if (isFacetModel(model)) {
     const facetName = model.getName('facet');
 
-    // Derive new sort index field for facet's sort array
-    head = CalculateNode.parseAllForSortIndex(head, model);
```
Comment (kanitw) [inline src/compile/data/parse.ts]: is this always wrong?

Comment (domoritz) [reply src/compile/data/parse.ts]: We add it above since already. I think it is.
