### PR TITLE
Make zindex for axis work again

### LINKED ISSUE #3537: zindex appears broken as of 2.3.x
As of version 2.3.x, [`zindex`](https://vega.github.io/vega-lite/docs/axis.html#general) no longer works as expected. 

In the following example spec, it would be expected that the (purposefully) black grid lines would be in front of the bar mark. No matter whether one puts 0 or 1, nothing happens.

```javascript
{
  "$schema": "https://vega.github.io/schema/vega-lite/v2.json",
  "description": "A simple bar chart with embedded data.",
  "data": {
    "values": [
      {"a": "A","b": 28}, {"a": "B","b": 55}, {"a": "C","b": 43},
      {"a": "D","b": 91}, {"a": "E","b": 81}, {"a": "F","b": 53},
      {"a": "G","b": 19}, {"a": "H","b": 87}, {"a": "I","b": 52}
    ]
  },
  "mark": "bar",
  "encoding": {
    "x": {"field": "a", "type": "ordinal"},
    "y": {"field": "b", "type": "quantitative", "axis":{"zindex":1}}
  },
  "config": {
    "axis": {
      "gridColor": "black"
    }
  }
}
```

image

### PR DESCRIPTION
**Pull request by kanitw**
Fix #3537

### CODE REVIEW

File: src/compile/axis/assemble.ts [hunk 1]
```diff
@@ -21,7 +21,7 @@ export function assembleAxis(
     header: boolean // whether this is called via a header
   } = {header: false}
 ): VgAxis {
-  const {orient, scale, title, ...axis} = axisCmpt.combine();
+  const {orient, scale, title, zindex, ...axis} = axisCmpt.combine();
```
Comment (domoritz) [inline src/compile/axis/assemble.ts]: How do we ensure that we don't forget anything here in the future?

Comment (kanitw) [reply src/compile/axis/assemble.ts]: If you look at the code below, that's probably the only thing left that's not specific to grid / main axis.
