### PR TITLE
fix: don't set guide label formats in encode blocks

### LINKED ISSUE #6398: Change how we generate formats to allow Vega to generate accessible labels
Vega's automatic description of guides does not take into account when the labels of an axis are formatted through an expression in the encode block. 

Unfortunately, Vega-Lite makes heavy use of it.

## Case 1

```json
{
  "$schema": "https://vega.github.io/schema/vega-lite/v4.json",
  "data": {"url": "data/stocks.csv"},
  "transform": [{"filter": "datum.symbol==='GOOG'"}],
  "mark": "line",
  "encoding": {
    "x": {"field": "date", "type": "temporal", "axis": {"format": "%a"}},
    "y": {"field": "price", "type": "quantitative"}
  }
}
```

generates

```json
    {
      "scale": "x",
      "orient": "bottom",
      "grid": false,
      "title": "date",
      "labelFlush": true,
      "labelOverlap": true,
      "tickCount": {"signal": "ceil(width/40)"},
      "encode": {
        "labels": {
          "update": {"text": {"signal": "timeFormat(datum.value, '%a')"}}
        }
      },
      "zindex": 0
    },
```

## Case 2

```json
{
  "$schema": "https://vega.github.io/schema/vega-lite/v4.json",
  "data": {"url": "data/seattle-weather.csv"},
  "mark": "bar",
  "encoding": {
    "x": {
      "timeUnit": "month",
      "field": "date",
      "type": "temporal"
    },
    "y": {
      "aggregate": "mean",
      "field": "precipitation",
      "type": "quantitative"
    }
  }
}
```

generates

```json
    {
      "scale": "x",
      "orient": "bottom",
      "grid": false,
      "title": "date (month)",
      "labelFlush": true,
      "labelOverlap": true,
      "encode": {
        "labels": {
          "update": {
            "text": {
              "signal": "timeFormat(datum.value, timeUnitSpecifier([\"month\"], {\"year-month\":\"%b %Y \",\"year-month-date\":\"%b %d, %Y \"}))"
            }
          }
        }
      },
      "zindex": 0
    },
```

In case 1, we could change Vega-Lite to use the standard format parameter of an axis but case 2 is a bit trickier. The issue is that Vega-Lite has a different default for time unit specifiers.

Maybe I'm not understanding time formatting correctly but I don't see a way to achieve what we need with just `format` and `formatType`. 

This, for example, isn't valid (and omits that we want to format a `month`).

Screen Shot 2020-04-24 at 09 39 17

Adding @haldenl who revised time unit support in Vega-Lite.

### PR DESCRIPTION
**Pull request by domoritz**
fixes #6398

~~Merge after #6391~~

### CODE REVIEW

File: src/compile/legend/assemble.ts [hunk 1]
```diff
@@ -74,12 +73,7 @@ export function assembleLegend(legendCmpt: LegendComponent) {
   }
 
   if (labelExpr !== undefined) {
-    let expr = labelExpr;
-    if (legend.encode?.labels?.update?.text && isSignalRef(legend.encode.labels.update.text)) {
-      expr = replaceAll(labelExpr, 'datum.label', legend.encode.labels.update.text.signal);
-    }
-
-    setLegendEncode(legend, 'labels', 'text', {signal: expr});
+    setLegendEncode(legend, 'labels', 'text', {signal: labelExpr});
```
Comment (kanitw) [inline src/compile/legend/assemble.ts:76]: Just like in axis, I don't think we should drop this.

File: src/compile/format.ts [hunk 2]
```diff
@@ -1,114 +1,150 @@
...
+
+export function formatGuide(
+  fieldOrDatumDef: FieldDef<string> | DatumDef<string>,
+  type: Type,
+  format: string | object,
+  formatType: string,
+  config: Config,
+  omitTimeFormatConfig: boolean // axis doesn't use config.timeFormat
+) {
+  if (isFieldOrDatumDefWithCustomTimeFormat(fieldOrDatumDef, config)) {
```
Comment (kanitw) [inline src/compile/format.ts:133]: What if the spec has a  custom `formatType` but config doesn't allow it?

It seems like we're not handling this here?  

(If you agree this is wrong, we can do this in a separate PR since I think previously we didn't handle this 100% correct either.)

File: test/compile/axis/assemble.test.ts [hunk 3]
```diff
@@ -51,23 +51,6 @@ describe('compile/axis/assemble', () => {
       expect(axis.title).toBe('Max of a, Min of b');
     });
 
-    it('correctly applies labelExpr', () => {
```
Comment (kanitw) [inline test/compile/axis/assemble.test.ts:54]: Don't remove this.

**Comment by domoritz** [comment]
> test is still failing

It depends on the new Vega release.

File: src/compile/axis/assemble.ts [hunk 4]
```diff
@@ -151,12 +151,7 @@ export function assembleAxis(
     }
 
     if (labelExpr !== undefined) {
-      let expr = labelExpr;
-      if (axis.encode?.labels?.update && isSignalRef(axis.encode.labels.update.text)) {
-        expr = replaceAll(labelExpr, 'datum.label', axis.encode.labels.update.text.signal);
-      }
-
-      setAxisEncode(axis, 'labels', 'text', {signal: expr});
+      setAxisEncode(axis, 'labels', 'text', {signal: labelExpr});
```
[the remark this answers is not in the document]
Comment (domoritz) [reply src/compile/axis/assemble.ts:154]: You can still use format but it's directly set to the axis now. I'm not following what the issue is here.

[the remark this answers is not in the document]
Comment (kanitw) [reply src/compile/axis/assemble.ts:154]: Ok, datum.label shouldn't exist anymore so this is correct (no need to replace).

File: src/compile/legend/assemble.ts (hunk 1 above)
Comment (kanitw) [reply src/compile/legend/assemble.ts:76]: NVM, it's ok to remove this.

**Comment by kanitw** [comment]
Some comments are still unaddressed.


Btw, I wonder which feature in the pending Vega this branch require?

**Comment by kanitw** [comment]
I also don't think we should merge this in the aria branch since it's a fix that can be done before.  (We can merge into `vg5.11`)

**Comment by domoritz** [comment]
> I also don't think we should merge this in the aria branch since it's a fix that can be done before. (We can merge into vg5.11)

I did this because it's a fix that is relevant to accessibility support. Without this change, guide VoiceOver descriptions are not formatted correctly. 

My vote would be for merging the ARIA changes before merging this change. Makes sense?

File: src/compile/format.ts [hunk 5]
```diff
@@ -1,114 +1,150 @@
...
-      return {signal: `isValid(${field}) ? ${field} : ""+${field}`};
+      return vgField(fieldOrDatumDef, {expr});
     }
+  } else {
+    return datumDefToExpr(fieldOrDatumDef);
   }
-  return undefined;
+}
+
+export function formatCustomType({
```
[the remark this answers is not in the document]
Comment (domoritz) [reply src/compile/format.ts:97]: Fixed

File: src/compile/axis/parse.ts [hunk 6]
```diff
@@ -305,10 +304,8 @@ function parseAxis(channel: PositionScaleChannel, model: UnitModel): AxisCompone
 
     const axisEncodingPart = guideEncodeEntry(axisEncoding[part] ?? {}, model);
 
-    const value = part === 'labels' ? encode.labels(model, channel, axisEncodingPart) : axisEncodingPart;
-
-    if (value !== undefined && keys(value).length > 0) {
-      e[part] = {update: value};
+    if (axisEncodingPart !== undefined && keys(axisEncodingPart).length > 0) {
```
[the remark this answers is not in the document]
Comment (domoritz) [reply src/compile/axis/parse.ts:307]: Right, this does not work anymore

```json
{
  "$schema": "https://vega.github.io/schema/vega-lite/v4.json",
  "data": {"url": "data/stocks.csv"},
  "transform": [{"filter": "datum.symbol==='GOOG'"}],
  "mark": "line",
  "encoding": {
    "x": {"field": "date", "type": "temporal", "axis": {"format": "%Y %b"}},
    "y": {"field": "price", "type": "quantitative", "axis": {"format": "0.2f", "formatType": "myFormat"}}
  },
  "config": {
    "customFormatTypes": true
  }
}
```

File: src/compile/format.ts (hunk 2 above)
Comment (kanitw) [reply src/compile/format.ts:142]: Let's handle this in a separate PR for https://github.com/vega/vega-lite/issues/6382

**Comment by domoritz** [comment]
Thank you @kanitw ❤️
