### PR TITLE
fix: don't generate label align when angle is 0 for top or bottom axis

### LINKED ISSUE #6341: Setting label angle removes label flush
Setting the label angle removes label flush. We could say that this is by design but it's a bit jarring. Not sure whether this is a regression either. 

[Open the Chart in the Vega Editor](https://vega.github.io/editor/#/url/vega-lite/N4KABGBEAkDODGALApgWwIaQFxUQFzwAdYsB6UgN2QHN0A6agSz0QFcAjOxge1IRQyUa6ALQAbZskoAWOgCtY3AHaQANOCgATZAgBOjQnh4qckAIJhYjVITHIw7dLrBIneMAHdmiMGnbJNbU0wTXQ8ejUNSFDw7DBQCAhICnQxVh04gG0NRPjITFMzNSh2OIAmAA4AX1U8gqgAIWLIUpwAVjaaurjIAGFm1rBpAGYanMTgfJ6AEQG4gE4ARi7J+sgAUTmcCuXa1Z6AMS2wNtH1XIh90wBxY8X5lanTAAljioB2R7WASWO2sqq4wAuhoxkkMLoANY9Ry6SJJZBKeDcTSMJTUOIJRKQAAemMgADNGMgxJoYc08ABPQjIHoAR1Y6CURnCRiozXQOMYsHxYnQ-jEZnRdjiAAYqoCIIDAUA)

### PR DESCRIPTION
**Pull request by domoritz**
fixes #6341

### CODE REVIEW

File: src/compile/axis/assemble.ts [hunk 1]
```diff
@@ -158,6 +158,11 @@ export function assembleAxis(
       setAxisEncode(axis, 'labels', 'text', {signal: expr});
     }
 
+    // clear default label align so label flush still works
+    if (axis.labelAngle === 0 && (orient === 'top' || orient === 'bottom') && axis.labelAlign === 'center') {
+      delete axis.labelAlign;
```
Comment (kanitw) [inline src/compile/axis/assemble.ts:163]: This is too hacky.  Setting it in parse and removing it later would make it really hard to reason about. 
Also, what if I make labelFlush = false, shouldn't we still set textAlign here?

, and wouldn't be correct in all cases. 

I'd rather make labelAlign/labelBaseline also depends on labelFlush. 
Basically if labelFlush is true, then don't set labelAlign for x / labelBaseline for y.

You can extract labelFlush to be AxisRuleParams, just like we do with labelAngle.

Comment (domoritz) [reply src/compile/axis/assemble.ts:163]: I did that but when I returned `undefined` in the case where I didn't want to set it, then the resolution logic would fill in the wrong value. I could return `null` instead of undefined, I guess.

Comment (domoritz) [reply src/compile/axis/assemble.ts:163]: The issue with `null` is that we need to clean it up later.

Comment (kanitw) [reply src/compile/axis/assemble.ts:163]: I think cleaning up null is more reasonable than setting other values then delete?

At least, we can consistently set null for both signal and normal cases.  (And only clean up in normal cases.)

**Comment by kanitw** [comment]
@domoritz -- can you do this by forking from https://github.com/vega/vega-lite/pull/6312?
