### PR TITLE
[WIP] Sw/fix multi bin

### LINKED ISSUE #1747: Cannot bin the same field twice
`Uncaught Error: Duplicate signal name: Rotten_Tomatoes_Rating_extent`

### PR DESCRIPTION
**Pull request by NeelMohapatra**
Fixes #1747

### CODE REVIEW

File: src/compile/data/bin.ts [hunk 1]
```diff
@@ -19,36 +19,42 @@ function numberFormatExpr(expr: string, format: string) {
...
-
-      const transform: VgTransform[] = [];
-      if (!binTrans.extent) {
-        const extentSignal = model.getName(fieldDef.field + '_extent');
-        transform.push({
-          type: 'extent',
+      const key = hash(bin) + fieldDef.field;
+      // FIXME: Check
+      if (!binComponent[key]) {
+        let binTrans: VgTransform = {
```
Comment (domoritz) [inline src/compile/data/bin.ts]: why not const?

File: src/compile/data/bin.ts [hunk 2]
```diff
@@ -19,36 +19,42 @@ function numberFormatExpr(expr: string, format: string) {
 function parse(model: Model): Dict<VgTransform[]> {
   return model.reduceFieldDef(function(binComponent: Dict<VgTransform[]>, fieldDef: FieldDef, channel: Channel) {
     const bin = model.fieldDef(channel).bin;
+    // Make this bin variable always an object
+    // and extend it with maxbins if needed here.
+    let transform: VgTransform[] = [];
```
Comment (domoritz) [inline src/compile/data/bin.ts]: const?

File: src/compile/data/bin.ts [hunk 3]
```diff
@@ -19,36 +19,42 @@ function numberFormatExpr(expr: string, format: string) {
...
-        typeof bin === 'boolean' ? {} : bin
-      );
-
-      const transform: VgTransform[] = [];
-      if (!binTrans.extent) {
-        const extentSignal = model.getName(fieldDef.field + '_extent');
-        transform.push({
-          type: 'extent',
+      const key = hash(bin) + fieldDef.field;
+      // FIXME: Check
```
Comment (domoritz) [inline src/compile/data/bin.ts]: check what?

File: src/compile/data/bin.ts [hunk 4]
```diff
@@ -19,36 +19,42 @@ function numberFormatExpr(expr: string, format: string) {
...
+          transform.push({
+            type: 'extent',
+            field: fieldDef.field,
+            signal: extentSignal
+          });
+
+          binTrans.extent = {signal: extentSignal};
+        }
+
+        //
```
Comment (domoritz) [inline src/compile/data/bin.ts]: what do you want to say?

File: src/compile/data/bin.ts [hunk 5]
```diff
@@ -19,36 +19,42 @@ function numberFormatExpr(expr: string, format: string) {
...
+        if (!binTrans.maxbins && !binTrans.step) {
+          // if both maxbins and step are not specified, need to automatically determine bin
+          binTrans.maxbins = autoMaxBins(channel);
+        }
+
+        transform.push(binTrans);
+      } else {
+        transform = binComponent[key].slice();
```
Comment (domoritz) [inline src/compile/data/bin.ts]: what are you slicing here?

File: typings/vega-util.d.ts [hunk 6]
```diff
@@ -22,7 +22,7 @@ declare module 'vega-util' {
   export function truncate(a: string, length: number): string;
 
   export function isArray(a: any | any[]): a is any[];
-  export function isObject(a: any): a is any;
+  export function isObject(a: any): a is Object;
```
Comment (domoritz) [inline typings/vega-util.d.ts]: I think you mean `object`? Why change this? Also, this is a ts 2.2 feature.

Comment (NeelMohapatra) [inline typings/vega-util.d.ts]: I think @kanitw suggested that

Comment (kanitw) [inline typings/vega-util.d.ts]: Actually I did try that with you and it *did not* work yet. Instead we used isBoolean, so we don't need this.  

That said, we should change this later when we upgrade to TS2.2 as the original `is any` is also wrong.

File: src/compile/data/bin.ts [hunk 7]
```diff
@@ -83,7 +88,7 @@ export const bin: DataComponentCompiler<Dict<VgTransform[]>> = {
     // If child doesn't have its own data source, then merge
     if (!childDataComponent.source) {
       // FIXME: current merging logic can produce redundant transforms when a field is binned for color and for non-color
-      extend(binComponent, childDataComponent.bin);
+      binComponent = {...childDataComponent.bin};
```
Comment (kanitw) [inline src/compile/data/bin.ts]: This does not have the same logic as the old one.

File: src/compile/data/bin.ts [hunk 8]
```diff
@@ -97,7 +102,7 @@ export const bin: DataComponentCompiler<Dict<VgTransform[]>> = {
 
       // If child doesn't have its own data source, then merge
       if (!childDataComponent.source) {
-        extend(binComponent, childDataComponent.bin);
+        binComponent = {...childDataComponent.bin};
```
Comment (kanitw) [inline src/compile/data/bin.ts]: This does not have the same logic as the old one.

File: src/compile/data/bin.ts (hunk 7 above)
Comment (kanitw) [inline src/compile/data/bin.ts]: The equivalent code to the old code would be

```
binComponent = {
  ...binComponent,
  ...childDataComponent.bin
}
```

That said, I think when we want to cause side effect the old `extend` method seems better.  
(I take back my comment from slack this morning.)

File: src/compile/data/bin.ts [hunk 9]
```diff
@@ -65,7 +71,6 @@ function parse(model: Model): Dict<VgTransform[]> {
         });
       }
       // FIXME: current merging logic can produce redundant transforms when a field is binned for color and for non-color
```
Comment (kanitw) [inline src/compile/data/bin.ts]: Outdated FIXME -- You are fixing this issue, so you should remove FIXME from the code.

File: src/compile/data/bin.ts (hunk 1 above)
Comment (kanitw) [inline src/compile/data/bin.ts]: Currently this is  extended with `extent` below.

Also, this spread code is poorly formatted. 

This is way better:

```
let binTrans: VgTransform = {
   type: bin, 
   field: fieldDef.field,
   as: [field(fieldDef, {binSuffix: 'start'}), field(fieldDef, {binSuffix: 'end'})], 
   ...(isBoolean(bin) ? {} : bin}
}
```

You can also make it const 

```
let binTrans: VgTransform = {
   type: bin, 
   field: fieldDef.field,
   as: [field(fieldDef, {binSuffix: 'start'}), field(fieldDef, {binSuffix: 'end'})], 
   ...(isBoolean(bin) ? {} : bin},
   // add extent if it's not specified
   ...(isBoolean(bin) || bin.extent === undefined ? {} : {extent: {signal: extentSignal}})
}
```

This would require minor code reordering and revision (hint: revise `if (!binTrans.extent) {` below), but this should be very simple to do.  I'm gonna leave that for you to figure out as it should be a good exercise for you.

File: src/compile/data/bin.ts [hunk 10]
```diff
@@ -19,36 +19,42 @@ function numberFormatExpr(expr: string, format: string) {
 function parse(model: Model): Dict<VgTransform[]> {
   return model.reduceFieldDef(function(binComponent: Dict<VgTransform[]>, fieldDef: FieldDef, channel: Channel) {
     const bin = model.fieldDef(channel).bin;
+    // Make this bin variable always an object
```
Comment (kanitw) [inline src/compile/data/bin.ts]: The comment here is obviously left from our prior discussion. 

Your code is still incorrect when you apply bin to two channels, and each of them gets different auto `maxbins` parameters.  In that case, your code should produce two separate bin transform since the parameter is different. 

You should add a new test case to test this case.

**Comment by kanitw** [comment]
Also, look at the codecov diff to make sure that you add test for all the cases.

File: src/compile/data/bin.ts [hunk 11]
```diff
@@ -18,37 +18,41 @@ function numberFormatExpr(expr: string, format: string) {
 
 function parse(model: Model): Dict<VgTransform[]> {
   return model.reduceFieldDef(function(binComponent: Dict<VgTransform[]>, fieldDef: FieldDef, channel: Channel) {
-    const bin = model.fieldDef(channel).bin;
+    const fieldDefBin = model.fieldDef(channel).bin;
+    const bin: Bin = isBoolean(fieldDefBin) ? {} : fieldDefBin;
+    if (bin && !(<VgTransform>bin).maxbins && !(<VgTransform>bin).steps) {
```
Comment (kanitw) [inline src/compile/data/bin.ts]: 1) You have to check if bin is defined or not first.  If not there is no point processing the rest. 

2) These casting `<VgTransform>` seem totally out of place.

File: src/compile/data/bin.ts [hunk 12]
```diff
@@ -18,37 +18,41 @@ function numberFormatExpr(expr: string, format: string) {
...
+      (<VgTransform>bin).maxbins = autoMaxBins(channel);
+    }
+    // Make this bin variable always an object
```
Comment (kanitw) [inline src/compile/data/bin.ts]: out of place comment

File: src/compile/data/bin.ts [hunk 13]
```diff
@@ -18,37 +18,41 @@ function numberFormatExpr(expr: string, format: string) {
...
-          field: fieldDef.field,
-          signal: extentSignal
-        });
-
-        binTrans.extent = {signal: extentSignal};
+      const key = hash(bin) + '_' + fieldDef.field;
+      if (binComponent[key]) {
+        transform.push.apply(transform, binComponent[key]); // concat in place
+      } else {
+        const checkExtentAbsent: boolean = !bin.extent;
```
Comment (kanitw) [inline src/compile/data/bin.ts]: This variable makes it harder to read the code, just simply remove it and use `!bin.extent`

File: src/compile/data/bin.ts [hunk 14]
```diff
@@ -18,37 +18,41 @@ function numberFormatExpr(expr: string, format: string) {
...
-        transform.push({
-          type: 'extent',
-          field: fieldDef.field,
-          signal: extentSignal
-        });
-
-        binTrans.extent = {signal: extentSignal};
+      const key = hash(bin) + '_' + fieldDef.field;
+      if (binComponent[key]) {
+        transform.push.apply(transform, binComponent[key]); // concat in place
```
Comment (kanitw) [inline src/compile/data/bin.ts]: this line seems unnecessary convoluted

Comment (kanitw) [inline src/compile/data/bin.ts]: If binComponent already has that key, I don't think you should do anything to transform here.   In fact, I would put `transform` inside the else case and no longer do `binComponent[key] = transform;`  at the end.

File: src/compile/data/bin.ts [hunk 15]
```diff
@@ -16,57 +16,62 @@ function numberFormatExpr(expr: string, format: string) {
...
-        const extentSignal = model.getName(fieldDef.field + '_extent');
-        transform.push({
-          type: 'extent',
-          field: fieldDef.field,
-          signal: extentSignal
-        });
-
-        binTrans.extent = {signal: extentSignal};
-      }
+function checkDiscreteDomainOrLegend(model: Model, transform: VgTransform[], fieldDef: FieldDef, channel: Channel) {
```
Comment (kanitw) [inline src/compile/data/bin.ts]: `addRangeFormulaForDiscreteDomainOrLegend` or `addRangeFormula` would be a more descriptive name for this method.

File: src/compile/data/bin.ts [hunk 16]
```diff
@@ -16,57 +16,62 @@ function numberFormatExpr(expr: string, format: string) {
...
-        transform.push({
-          type: 'formula',
-          as: field(fieldDef, {binSuffix: 'range'}),
-          expr: `${numberFormatExpr(startField, format)} + ' - ' + ${numberFormatExpr(endField, format)}`
-        });
+function parse(model: Model): Dict<VgTransform[]> {
+  return model.reduceFieldDef(function(binComponent: Dict<VgTransform[]>, fieldDef: FieldDef, channel: Channel) {
+    const fieldDefBin = model.fieldDef(channel).bin;
+    if (fieldDefBin) {
+      // Make this bin variable always an object
```
Comment (kanitw) [inline src/compile/data/bin.ts]: Remove these two lines of comments as it was meant to be a TODO for you.

File: src/compile/data/bin.ts [hunk 17]
```diff
@@ -16,57 +16,62 @@ function numberFormatExpr(expr: string, format: string) {
...
+        if (!bin.extent) {
+          transform.push({
+            type: 'extent',
+            field: fieldDef.field,
+            signal: extentSignal
+          });
+        }
+        transform.push(binTrans);
+
+        checkDiscreteDomainOrLegend(model, transform, fieldDef, channel);
```
Comment (kanitw) [inline src/compile/data/bin.ts]: You can refactor code such that you only need to call this method once at the end.

File: src/compile/data/bin.ts [hunk 18]
```diff
@@ -16,57 +16,62 @@ function numberFormatExpr(expr: string, format: string) {
...
-          type: 'extent',
-          field: fieldDef.field,
-          signal: extentSignal
-        });
-
-        binTrans.extent = {signal: extentSignal};
-      }
+function checkDiscreteDomainOrLegend(model: Model, transform: VgTransform[], fieldDef: FieldDef, channel: Channel) {
+  const hasDiscreteDomainOrHasLegend = hasDiscreteDomain(model.scale(channel).type) || model.legend(channel);
+  if (hasDiscreteDomainOrHasLegend) {
```
Comment (kanitw) [inline src/compile/data/bin.ts]: You haven't checked if the range formula has already been added.  

Hint: if it's added, it's always the last item in the array.

File: test/compile/data/bin.test.ts [hunk 19]
```diff
@@ -49,14 +49,14 @@ describe('compile/data/bin', function() {
         assert.deepEqual(transform[0], {
           type: 'extent',
           field: 'Acceleration',
-          signal: 'Acceleration_extent'
+          signal: '{"maxbins":10}_Acceleration_extent'
```
Comment (domoritz) [inline test/compile/data/bin.test.ts]: is this a valid signal name?

Comment (kanitw) [inline test/compile/data/bin.test.ts]: Nope.  Valid signal name should be a valid javascript variable name.

**Comment by kanitw** [comment]
@NeelMohapatra Please address the signal name issue and add tests for others and commit all of them at once.

**Comment by kanitw** [comment]
- [ ] There is actually another problem when the same field has multiple bin parameters.  The output data still uses the same `bin` field.   This is definitely important to make this work, but I'm also okay if you wanna separate this issue into another PR.

**Comment by kanitw** [comment]
Before tomorrow, focus on the fixing the signal and make test pass.  

Then think about how would you solve the problem I've just mentioned: 

> There is actually another problem when the same field has multiple bin parameters. The output data still uses the same bin field. This is definitely important to make this work, but I'm also okay if you wanna separate this issue into another PR.

We can discuss about how you should fix this part tomorrow.

File: src/fielddef.ts [hunk 20]
```diff
@@ -147,7 +147,8 @@ export function field(fieldDef: FieldDef, opt: FieldRefOption = {}) {
 
     if (!opt.nofn) {
       if (fieldDef.bin) {
-        fn = 'bin';
+        const bin: Bin = isBoolean(fieldDef.bin) ? {} : {...fieldDef.bin};
```
Comment (kanitw) [inline src/fielddef.ts]: You forgot to handle the case that we automatically add autoCount to bin.  (Extract that part of that to binToString too)

File: src/bin.ts [hunk 21]
```diff
@@ -39,6 +39,15 @@ export interface Bin {
    */
   maxbins?: number;
 }
+export function binToString(bin: Bin) {
```
Comment (kanitw) [inline src/bin.ts]: rename to `binParamsString` (more descriptive)?

File: src/fielddef.ts (hunk 20 above)
Comment (kanitw) [inline src/fielddef.ts]: Actually, you need a separate method for that to make it correct inside transform.  Let's make a `getBinDef(bin: boolean | Bin): Bin`.

Comment (NeelMohapatra) [inline src/fielddef.ts]: Yeah, you're right. I'm taking notes from now on

**Comment by domoritz** [comment]
stacked_area_binned

Master
screen shot 2017-04-06 at 22 34 09

Your branch
screen shot 2017-04-06 at 22 34 30

**Comment by NeelMohapatra** [comment]
Ouch. Is it from the example vega spec?

**Comment by domoritz** [comment]
No, this is an example Vega-Lite spec. Looks like something with the order got messed up.

File: src/fielddef.ts [hunk 22]
```diff
@@ -250,6 +252,11 @@ export function defaultType(fieldDef: FieldDef, channel: Channel): Type {
 export function normalize(fieldDef: ChannelDef, channel: Channel) {
   // If a fieldDef contains a field, we need type.
   if (isFieldDef(fieldDef)) { // TODO: or datum
+    // TODO: swojit - you can normalize bin here
```
Comment (kanitw) [inline src/fielddef.ts]: When you finish some TODO, remove the TODO

File: src/fielddef.ts [hunk 23]
```diff
@@ -250,6 +252,11 @@ export function defaultType(fieldDef: FieldDef, channel: Channel): Type {
...
+    if (!!fieldDef.bin) {
+      fieldDef.bin = isBoolean(fieldDef.bin) ? {maxbins: 10} : fieldDef.bin;
```
Comment (kanitw) [inline src/fielddef.ts]: This is causing side effect. Below, I already modified this method to cause no side effect to provide an example for you.  Please follow that.

Comment (kanitw) [inline src/fielddef.ts]: (Actually, there is one case I forgot to change it to prevent side effect, please fix that too.)

File: src/fielddef.ts [hunk 24]
```diff
@@ -250,6 +252,14 @@ export function defaultType(fieldDef: FieldDef, channel: Channel): Type {
 export function normalize(fieldDef: ChannelDef, channel: Channel) {
   // If a fieldDef contains a field, we need type.
   if (isFieldDef(fieldDef)) { // TODO: or datum
+    // TODO: swojit - you can normalize bin here
+    if (fieldDef.bin) {
+      fieldDef.bin = isBoolean(fieldDef.bin) ? {maxbins: 10} : fieldDef.bin;
```
Comment (kanitw) [inline src/fielddef.ts]: This is still causing side effect to the existing bin object.  As I show below for type you should do something like:
```
fieldDef = {
   ...fieldDef,
   bin: {
    maxbins: 10,
    ...(isBoolean(fieldDef.bin) ? {} : fieldDef.bin)
   }
}
```

File: src/compile/data/bin.ts [hunk 25]
```diff
@@ -16,60 +16,59 @@ function numberFormatExpr(expr: string, format: string) {
...
+        binComponent[key] = transform = [];
+        const extentSignal = model.getName(key + '_extent');
+
+        let binTrans: VgBinTransform = {
+            type: 'bin',
+            field: fieldDef.field,
+            as: [field(fieldDef, {binSuffix: 'start'}), field(fieldDef, {binSuffix: 'end'})],
+            signal: varName(model.getName(key + '_bins'))
+        };
+        extend(binTrans, bin); // Has side effect. TODO: Try to remove them
```
Comment (kanitw) [inline src/compile/data/bin.ts]: As mentioned on slack please just avoid side effect
```
let binTrans: ... = extend({ 
  ...
}, bin);
```

File: src/compile/data/bin.ts [hunk 26]
```diff
@@ -16,60 +16,59 @@ function numberFormatExpr(expr: string, format: string) {
...
-        as: [field(fieldDef, {binSuffix: 'start'}), field(fieldDef, {binSuffix: 'end'})],
-        signal: varName(model.getName(fieldDef.field + '_bins'))
-      };
-
-      if (!isBoolean(bin)) {
-         binTrans = extend(binTrans, bin);
+    const fieldDefBin = model.fieldDef(channel).bin;
+    if (fieldDefBin) {
+      const bin: Bin = isBoolean(fieldDefBin) ? {} : fieldDefBin;
+      if (!bin.maxbins && !bin.steps) {
```
Comment (kanitw) [inline src/compile/data/bin.ts]: If we already initialize this in unit, why do we have to augment the value again here?

File: src/fielddef.ts [hunk 27]
```diff
@@ -250,6 +252,13 @@ export function defaultType(fieldDef: FieldDef, channel: Channel): Type {
 export function normalize(fieldDef: ChannelDef, channel: Channel) {
   // If a fieldDef contains a field, we need type.
   if (isFieldDef(fieldDef)) { // TODO: or datum
+    if (fieldDef.bin) {
+      fieldDef.bin = isBoolean(fieldDef.bin) ? {maxbins: 10} : fieldDef.bin;
```
Comment (kanitw) [inline src/fielddef.ts]: 1) As I have commented twice ([1](https://github.com/vega/vega-lite/pull/1983#discussion_r110508590) and [2](https://github.com/vega/vega-lite/pull/1983#discussion_r110524611)), please don't cause side effect!

2) Why don't you bring back `autoMaxBins` and call it here?  Now we got channel in the context and thus we don't really have to remove it. 

3) If you have a convincing reason why you should not bring  `autoMaxBins` back, at least use the default `maxbins` config here.  (If you use the old `autoMaxBins`, just get rid of the `maxbins` config for now.

File: src/fielddef.ts [hunk 28]
```diff
@@ -250,6 +252,13 @@ export function defaultType(fieldDef: FieldDef, channel: Channel): Type {
...
+      if (!fieldDef.bin.maxbins) {
```
Comment (kanitw) [inline src/fielddef.ts]: Incorrect logic.  If there is `step`, no need to insert maxbins.

File: test/compile/data/bin.test.ts [hunk 29]
```diff
@@ -50,18 +50,60 @@ describe('compile/data/bin', function() {
...
+          as: ["bin_maxbins_10_Acceleration_start", "bin_maxbins_10_Acceleration_end"],
           maxbins: 10,
-          signal: "Acceleration_bins",
-          extent: {signal: 'Acceleration_extent'}
+          signal: "bin_maxbins_10_Acceleration_bins",
+          extent: {signal: 'bin_maxbins_10_Acceleration_extent'}
         });
       });
     });
+    describe('should bin the same field', () => {
```
Comment (kanitw) [inline test/compile/data/bin.test.ts]: why using `describe` here?  This definitely looks like an `it`.

Also please update description to be clearer (like `it('should ... when two channels encode the same binned field', `)

File: test/compile/data/bin.test.ts [hunk 30]
```diff
@@ -50,18 +50,60 @@ describe('compile/data/bin', function() {
...
+            type: "quantitative"
+          },
+          size: {
+            aggregate: "count",
+            field: "*",
+            type: "q"
+          }
+        }
+      });
+      const transform = vals(bin.parseUnit(model))[0];
```
Comment (kanitw) [inline test/compile/data/bin.test.ts]: You test here doesn't even check the field that is used twice!  

Make sure to (1) check that and (2) check that the output bin component only has two items (not three!)

Comment (NeelMohapatra) [inline test/compile/data/bin.test.ts]: Can it be done only by checking the transform? `Rotten Tomato Rating` doesn't appear anywhere in the transform array

Comment (kanitw) [inline test/compile/data/bin.test.ts]: Why do you wrap `bin.parseUnit(model)` with `vals(...)[0]` (especially the `[0]` part)?

Comment (NeelMohapatra) [inline test/compile/data/bin.test.ts]: That was by mistake

File: test/compile/data/bin.test.ts [hunk 31]
```diff
@@ -12,53 +12,142 @@ describe('compile/data/bin', function() {
...
+          as: ['bin_maxbins_10_Acceleration_start', 'bin_maxbins_10_Acceleration_end'],
           maxbins: 10,
-          signal: "Acceleration_bins",
-          extent: {signal: 'Acceleration_extent'}
+          signal: 'bin_maxbins_10_Acceleration_bins',
+          extent: {signal: 'bin_maxbins_10_Acceleration_extent'}
+        });
+      });
+    });
+    describe('same field encoded twice', () => {
```
Comment (kanitw) [inline test/compile/data/bin.test.ts]: As I just commented [earlier today](https://github.com/vega/vega-lite/pull/1983#discussion_r110553917), this should be `it`. 

I know then you wanna complain why are there similarly weird `describe` above.  We actually discussed this in a meeting earlier and I told you that yeah these should be `it` too -- please help change them so you have good example tests to follow. 

To provide an example for you, this one could be
```js
it('should apply bin transform only once for a binned field encoded in multiple channels', 
```

File: test/compile/data/bin.test.ts [hunk 32]
```diff
@@ -12,53 +12,142 @@ describe('compile/data/bin', function() {
...
+            type: 'q'
+          }
+        }
+      });
+      const transformArray = bin.parseUnit(model);
+      const transformArrayVals = vals(transformArray);
+      const imdbTransform = transformArrayVals[0];
+      const rotten10Transform = transformArrayVals[1];
+      const rotten20Transform = transformArrayVals[2];
+      it('should be binned twice', function() {
```
Comment (kanitw) [inline test/compile/data/bin.test.ts]: This test and its description are a bit confusing.

1) The binned field that is encoded twice should be bin *once*, not twice.
2) The description is confusing partly because the test spec is a bit too complicated. Why do you need to include `x: IMDB_Rating` and `size: count`? I think better use just a minimal spec that demonstrates the thing you want to test.

File: test/compile/data/bin.test.ts (hunk 31 above)
Comment (NeelMohapatra) [inline test/compile/data/bin.test.ts]: Ah, I thought we needed both describe and it. My bad. I am on it

Comment (kanitw) [inline test/compile/data/bin.test.ts]: To remind, `describe` should be for grouping test suites (for namespaces and methods). 
`it` = test cases.

File: src/fielddef.ts [hunk 33]
```diff
@@ -251,6 +251,7 @@ export function defaultType(fieldDef: FieldDef, channel: Channel): Type {
  */
 export function normalize(fieldDef: ChannelDef, channel: Channel) {
   // If a fieldDef contains a field, we need type.
+  fieldDef = JSON.parse(JSON.stringify(fieldDef)); // Clone
```
Comment (NeelMohapatra) [inline src/fielddef.ts]: @kanitw I couldn't figure out a good way to remove side effects without cloning it. If you think there's one, I'll update it

File: test/compile/data/bin.test.ts [hunk 34]
```diff
@@ -45,110 +43,59 @@ describe('compile/data/bin', function() {
...
-          signal: 'bin_maxbins_20_Rotten_Tomatoes_Rating_bins',
-          maxbins: 20,
-          extent: {signal: 'bin_maxbins_20_Rotten_Tomatoes_Rating_extent'}
-        });
-        assert.deepEqual(rotten20Transform[2], {
-          type: 'formula',
-          as: 'bin_maxbins_20_Rotten_Tomatoes_Rating_range',
-          expr: 'format(datum["bin_maxbins_20_Rotten_Tomatoes_Rating_start"], \'s\') + \' - \' + format(datum["bin_maxbins_20_Rotten_Tomatoes_Rating_end"], \'s\')'
-        });
+      const transform = vals(bin.parseUnit(model))[0];
```
Comment (kanitw) [inline test/compile/data/bin.test.ts]: The test right now doesn't really check if it apply the bin only once.  Make sure to assert the length...

**Comment by domoritz** [comment]
🎉
