### PR TITLE
fix: correctly redirect align, baseline, dx, dy, and limit of config.title to config.style.group-subtitle

### LINKED ISSUE #6445: Subtitle configuration bug dx
# Bug
Subtitle **dx**  property is not working with {
"config": {
"title": {"dx":30}
}
but only works for
 "title": {"dx":30}}.

What is the difference of "title" and "config": {"title"} ?

# Examples
[Bug Example](https://vega.github.io/editor/#/url/vega-lite/N4Igxg9gdgZglgcxALlANzgUwO4tJKAFzigFcJSBnAdTgBNCALFAFgAY2AacaYsiygAlMiRoRQBmDgF9uxQgBtMeEAEMoYRhABOKEJUKrt47nQAekttNkg6qwyqiqAtsuS37qgLQBGGAA4ATgAmOjoAdkCANjoJKNVVILAAVkwYTFUoqJZ0-xS2EBtnIwBrFUIATwAHNxAAIyMQbko4AC83KKtuTA0IOhIkVBALIcqavQBHUnV5ezg0ZW54TAU6PQsbCvLq2qmZuENiBaaQZdW9Les5A6VyzDNxdwAVG8X9Ujr5W-cAZQ+v5Q2AAklE0mGKejEhCqlGQAHo4QsEKoAHQIA6MD4ouAQOGgxjg1SIzDIrwKA6YREsFH+FE+FEAK0o0BOdkMlEwhEoKjZ3j8QVCEWisXiiUCKTSGSyOUweWSBWQAG1QCMfNwtsgfNIALrWIA)
image
[Working Example](https://vega.github.io/editor/#/url/vega-lite/N4Igxg9gdgZglgcxALlANzgUwO4tJKAFzigFcJSBnAdTgBNCALFAFgAY2AacaYsiygAlMiRoRQBmDgF9uxQgBtMeEAEMoYRhABOKEJUKrt46bJB1VhlVFUBbZcnOXVAWgCMMABwBOAEx06AHZvADY6CRDVVR8wAFZMGExVEJCWRM84thAzWyMAaxVCAE8ABwcQACMjEG5KOAAvBxC2M0wNCDoSJFQQAA9C0vKAR1J1eUs4NGVueEwFOj1+syKBsr0RsbhDYimakFn5vRXTOS2lQsxe8UcAFTPp-VIK+XPHAGUnl4e6fuQpMwAJJRNJhcnoxIQSpRkAB6GFTBCqAB0CC2jCeSLgEBhwMYoNU8MwiJcCi2mHhLCRniRbiRACtKNA9hZDJRMIRKCoWa4PD5-EFQuFItFvHEEkkUmlMBlYllkABtUC-NzcFbINzSAC6piAA)
image

### PR DESCRIPTION
**Pull request by kanitw**
fix #6445

### CODE REVIEW

File: src/config.ts [hunk 1]
```diff
@@ -583,19 +583,24 @@ export function stripAndRedirectConfig(config: Config) {
...
-  };
-
-  // set config.style if it is not an empty object
-  if (keys(style).length > 0) {
-    config.style['group-title'] = style;
+  const {titleMarkConfig, subtitleMarkConfig, subtitle} = extractTitleConfig(config.title);
+
+  // set config.style if title/subtitleMarkConfig is not an empty object
+  if (keys(titleMarkConfig).length > 0) {
+    // TODO figure precedence
```
Comment (domoritz) [inline src/config.ts:590]: Why not do this here? Maybe file an issue instead of just a todo in the code.

Comment (kanitw) [reply src/config.ts]: forgot to remove.
