### PR TITLE
Make interfaces and schema for `FieldDef`, `ValueDef` more precise

### LINKED ISSUE #1861: Incorrect schema for Detail channel
Detail channel is for additional group-by/measure `field`s and thus does not support `value`.

### PR DESCRIPTION
**Pull request by kanitw**
Fix #1861 

`ChannelDef = FieldDef | ValueDef`

Rename `*ChannelDef` / `ChannelDef*` => `*FieldDef`
- `ChannelDefWithScale` => `ScaleFieldDef`
- `PositionChannelDef` => `PositionFieldDef`
- `ChannelDefWithLegend` => `LegendFieldDef`
- `OrderChannelDef` => `OrderFieldDef`

### CODE REVIEW

File: src/compile/config.ts [hunk 1]
```diff
@@ -87,7 +87,7 @@ export function orient(mark: Mark, encoding: Encoding, scale: Dict<Scale>, markC
       if (!hasDiscreteDomain(xScaleType) && (
             !encoding.y ||
             hasDiscreteDomain(yScaleType) ||
-            encoding.y.bin
+            (encoding.y as FieldDef).bin
```
Comment (domoritz) [inline src/compile/config.ts]: instead you could do `isFieldDef(encoding.y) && encoding.y.bin`

File: src/encoding.ts [hunk 2]
```diff
@@ -48,14 +49,14 @@ export interface UnitEncoding {
...
-  size?: ChannelDefWithLegend;
+  size?: LegendFieldDef | ValueDef<number>;
 
   /**
    * The symbol's shape (only for `point` marks). The supported values are
    * `"circle"` (default), `"square"`, `"cross"`, `"diamond"`, `"triangle-up"`,
    * or `"triangle-down"`, or else a custom SVG path string.
    */
-  shape?: ChannelDefWithLegend; // TODO: maybe distinguish ordinal-only
+  shape?: LegendFieldDef | ValueDef<string>; // TODO: maybe distinguish ordinal-only
```
Comment (domoritz) [inline src/encoding.ts]: `ValueDef<Shape|string>`? Maybe even better, change shape to be `'circle' | 'square' | 'cross' | 'diamond' | 'triangle-up' | 'triangle-down' | string`.

File: src/fielddef.ts [hunk 3]
```diff
@@ -84,12 +88,22 @@ export interface ChannelDefWithLegend extends ChannelDefWithScale {
...
 }
 
+export type ChannelDef = FieldDef | ValueDef<any>;
+
+export function isFieldDef(channelDef: ChannelDef): channelDef is FieldDef | PositionFieldDef | LegendFieldDef | OrderFieldDef  {
+  return channelDef && !!channelDef['field'];
+}
+
+export function isValueDef(channelDef: ChannelDef): channelDef is ValueDef<any> {
+  return channelDef && !!channelDef['value'];
```
Comment (domoritz) [inline src/fielddef.ts]: what is value is false? Wouldn't `'value' in channelDef` be better?

File: src/encoding.ts (hunk 2 above)
Comment (kanitw) [inline src/encoding.ts]: I disagree with this one.  There is no point doing `<string literals> | string`.

File: src/fielddef.ts (hunk 3 above)
Comment (kanitw) [inline src/fielddef.ts]: Good catch.  I change it to:
```
channelDef && 'value' in channelDef && channelDef['value'] !== undefined;
```

**Comment by kanitw** [comment]
@domoritz  Fixed two comments that I agreed and force pushed.

File: src/encoding.ts (hunk 2 above)
Comment (domoritz) [inline src/encoding.ts]: Well, we actually use `Shape | string` in https://github.com/vega/vega-lite/blob/f39a127d70248253c7ec4af93a1290ce9400cfd6/src/mark.ts#L203
