### PR TITLE
fix: use en dash for legend ranges

### LINKED ISSUE #5622: Make number range in legends consistent with Vega style
https://www.grammarly.com/blog/en-dash/

### PR DESCRIPTION
**Pull request by domoritz**
fixes #5622

### CODE REVIEW

File: src/compile/common.ts [hunk 1]
```diff
@@ -150,7 +150,7 @@ export function binFormatExpression(startField: string, endField: string, format
     startField,
     format,
     config
-  )} + " - " + ${numberFormatExpr(endField, format, config)}`;
```
Comment (kanitw) [inline src/compile/common.ts]: Make a constant called `BIN_RANGE_DELIMITER`?
