### PR TITLE
fix: incorrect boxplot when using temporal field

### LINKED ISSUE #4524: Unexpected offset of boxplots when filtering aggregated temporal data
Using the Boxplot mark when aggregating and filtering temporal data produces an unexpected  chart offset that varies depending on how far after 1970 values are filtered out. In the example below try changing `1985` to a later or earlier year.

The fact this only occurs beyond 1970 suggests there may be a time parsing issue somewhere. If the mark is changed to a primitive such as `circle`, there is no offset. 

```javascript
{
  "$schema": "https://vega.github.io/schema/vega-lite/v3.json",
  "width": 600,
  "data": {
    "url": "https://gicentre.github.io/data/temperatureAnomalies.json",
    "format": {"parse": {"Anomaly": "number"}}
  },
  "transform": [{"filter": "year(datum.Date) >= 1985"}],
  "encoding": {
    "x": {
      "field": "Date",
      "type": "temporal",
      "timeUnit": "year"
    },
    "y": {"field": "Anomaly", "type": "quantitative"}
  },
  "mark": "boxplot"
}
```

### LINKED ISSUE #4925: Boxplot missing/broken whiskers when using timeUnit
When I try to group data by weekday or month (or any `timeUnit`) and use `"extent": "min-max"`, whiskers are displayed, but when using the default 1.5 IQR, no whiskers are drawn. If I switch to `ordinal` or `nominal` types, detached whiskers are drawn in a new column. This seems to be related to issue #4524 

image

image

image

```json
{
  "$schema": "https://vega.github.io/schema/vega-lite/v3.2.1.json",
  "hconcat": [
    {
      "data": {"url": "https://vega.github.io/vega-datasets/data/seattle-temps.csv"},
      "mark": {"type": "boxplot",  "extent": "min-max"},
      "encoding": {
        "x": {"type": "temporal", "field": "date", "timeUnit": "month"},
        "y": {"type": "quantitative", "field": "temp"}
      }
    },
    {
      "data": {"url": "https://vega.github.io/vega-datasets/data/seattle-temps.csv"},
      "mark": "boxplot",
      "encoding": {
        "x": {"type": "temporal", "field": "date", "timeUnit": "month"},
        "y": {"type": "quantitative", "field": "temp"}
      }
    },
    {
      "data": {"url": "https://vega.github.io/vega-datasets/data/seattle-temps.csv"},
      "mark": "boxplot",
      "encoding": {
        "x": {"type": "ordinal", "field": "date", "timeUnit": "month"},
        "y": {"type": "quantitative", "field": "temp"}
      }
    }
  ]
}
```

### PR DESCRIPTION
**Pull request by chanwutk**
Fix #4524 
Fix #4925

Boxplot did not include `bins` and `timeUnits` transform into `filteredLayersMixins`' transform. So, I included them.

### CODE REVIEW

**Comment by chanwutk** [comment]
At line 244, do we need the if statement `if (boxPlotType === 'tukey')`?
`boxPlotType` is always either `'tukey'` or `'min-max'`, so in this line it is going to always be `'tukey'` because it is under another if (`if (boxPlotType !== 'min-max')`).

**Comment by domoritz** [comment]
> At line 244, do we need the if statement if (boxPlotType === 'tukey')?
boxPlotType is always either 'tukey' or 'min-max', so in this line it is going to always be 'tukey' because it is under another if (if (boxPlotType !== 'min-max')).

Good catch. Let's simplify the code. 

We can also simplify `if (outlierLayersMixins && filteredWhiskerSpec)` since `filteredWhiskerSpec` is always true.

File: src/compositemark/boxplot.ts [hunk 1]
```diff
@@ -300,17 +302,14 @@ export function normalizeBoxPlot(
       }
     })[0];
 
+    const filteredLayersMixinsTransforms = [...bins, ...timeUnits, joinaggregateTransform];
     if (outlierLayersMixins && filteredWhiskerSpec) {
```
Comment (domoritz) [inline src/compositemark/boxplot.ts:306]:
```suggestion
    if (outlierLayersMixins) {
```

Comment (domoritz) [reply src/compositemark/boxplot.ts:306]: If you simplify the code above.

**Comment by domoritz** [comment]
Thank you!
